se.sjoerd.DatMan.json

As the last object of a JSON object, appending a comma is against the JSON specification.

Remove excess comma in manifest

---

src/window.ui

A few Changes:
- Move the Graph Box out of "selection_box"
- use AdwFlap for the sidebar, moving the graph into the content child, the vertical separator to the separator child and the sidebar into flap
- Move the save button to the headerbar
- Use AdwExpanderRows for housing the buttons
- Use AdwEntryRows for input fields
- Housing all AdwExpanderRows in a ScrollWindow
- Removing a few " characters
Preview: 
Feel free to request changes

Proposal: UI changes

---

src/add_data_advanced.ui
src/add_equation_window.ui
src/open_special.ui
src/pip_mode.ui
src/plot_settings.ui
src/preferences.ui
src/rename_label_window.ui
src/sample_box.ui
src/transform_window.ui

Since the flatpak target is GNOME 43, which ships with libadwaita 1.2 and a few components in use are 1.1 or newer, there should be no downside to raising the requirement. Leaving it as is might lead to future errors in non-flatpak builds.

bump libadwaita requirement to 1.2

---

src/window.ui

- Have two GtkBoxes for buttons in the headerbar: one for actions at the start (add, undo, redo, select) and one at the end (save & primary)
- move everything into these Boxes
- change spacing to 5 pixels
- remove redundant GtkGrid, since all buttons formerly in it have been (re)moved. Also remove respective layout property of equation_scroll
- give the item list 50 more pixels

clean window.ui

---

data/ui/plot_settings.ui
src/plot_settings.py

Removes apply button from plot settings, and saves changes directly upon notify (so when a new dataset is selected) or when the plot settings are closed
Fixes issue #52

Remove apply button in plot settings, save changes directly upon notify instead

---

src/graphs.py
src/plot_settings.py
src/samplerow.py

This fixes a the bug where the rows get stuck in an active state on double click.
This is a known upstream GTK issue where rows can get stuck upon a double click action. I'm not completely sure where the problem lies, but it gets triggered when you double click an item and immediate pop over a modal window. I believe it has something to do with the window getting triggered on click, while the fade back to the non-active state for the row gets triggered upon release. But due to this modal window freezing the UI in the parent window, this release state is never triggered.
The workaround was to just trigger the modal window upon double release instead of double click. Where I had to use another workaround to emmit a release signal on GtkGesture. See bug report …

Fix stuck rows

---

src/graphs.py
src/item_operations.py
src/main.py
src/plotting_tools.py
src/toolbar.py

Switching modes and everything related to that is now handled by plotting_tools.set_mode().
We no longer simulate button presses on the dummy_toolbar but rely on functions deeper down the stack.
Thanks to this, mode switching is now a tad bit faster and reliable. 
Selecting a mode persists through graph.reload as well now.

change mode switching logic

---

data/ui/window.ui
src/graphs.py
src/window.py

Like suggested in https://github.com/SjoerdB93/Graphs/issues/54, the list box now grows dynamically with its content. When no content is present it remains hidden.

grow list view dynamically

---

src/plotting_tools.py

Fixes issue #89. Seems this is an upstream issue in the regular gtk4 backend, but it works fine for cairo.
No extra imports or packages are needed, Cairo needs requires [PyGObject](https://wiki.gnome.org/action/show/Projects/PyGObject) and [pycairo](https://www.cairographics.org/pycairo/) but it seems both are included in the standard runtimes (PyGObject obviously is, but I wasn't sure about pycairo before).
[Screencast from 2023-02-08 11-59-30.webm](https://user-images.githubusercontent.com/68477016/217512278-5cd9ef9e-8d3d-4b7b-8dc2-0d47ccfaaf17.webm)
Closes issue #89

Switch to cairo backend for figurecanvas

---

src/graphs.py
src/plotting_tools.py
src/utilities.py

This has a few changes to make this feature work:
- `DummyToolbar` Class based on `backend_bases` version of `NavigationToolbar`. This eliminates any unnecessary overhead from having unrendered gtk widgets, and gtk-releated stuff, that we don't use anyway. Since `backend_bases` does not implement the `draw_rubberband` function this is implemented as well (even more optimized than the upstream matplotlib implementation)
- A `_post_draw` classfunction in `PlotWidget`. This overrides matplotlibs implementation of a rubberband by hooking into existing code and just changing the way its actually rendered: using a full rectangle with a style-matching colour instead of a dashed rectangle like before.
Screenshot:

implement own rubberband zoom

---

data/ui/sample_box.blp
src/colorpicker.py
src/samplerow.py

Colorpicker is no longer dependant on Gtk.Button, instead taking the already compiled(?) button from samplerow.
This should help ease the transition for Gnome 44

Define color button in blueprint

---

src/file_io.py

When loading a project, that has been saved in Dark/Light mode in the respective other, the style remains. This sets the style based on config

Fix style when loading project

---

data/ui/plot_settings.blp
src/calculation.py
src/clipboard.py
src/operations.py
src/plot_settings.py
src/plotting_tools.py

Fixes some bugs, plus automatically fills in the current name of an item in the plot settings. I've found while working with Graphs that you often just want to change a small thing in the name (fix a typo for instance, or add some information). It's annoying if you have to retype the entire name. It's also more consistent with general behaviour to have the name filled in that field already, and let it react if the user changes is. (Such as already is the case with plot settings).
Fixes the following issues as well:
- Change of y-scale was broken as it was looking for graphs.graphs.refresh instead of graphs.refresh
- Y_range was not accesabile in transformation tools due to a capitalization issue
- Canvas limits are refreshed now after every operation (so that the graph doesn't dissapear …

Bugfixes + Fill in name automatically in plot settings

---

data/ui/plot_settings.blp

Tiny PR. Changes the wording in the dropdown menu of Plot Settings from "Data set ID" with subtitle "The data set to be edited" to "Selected Item" and "Choose which item to edit".
I'm happy for other suggestions, but the original wording is not exactly human friendly language, it kinda originated from the fact that most data that I open in Graphs are measurements from samples I've made in my PhD. All those samples have a specific ID which is usually the same as the filename. Which explains some other wordings I've been using internally ("Sample" for data for instance at times) in the beginning.

Change wording in plot setings

---

.github/workflows/main.yml

As the aarch64 github workflow seems broken, there doesn't seem to be much use to it at the moment. It only makes every single commit fail, defeating the purpose a bit of having this workflow in the first place.
Until we figure out what is wrong with this workflow, and if it's something we can fix ourselves, I propose we just build against x86 in the Github commits, and build for aarch64 for the Flathub releases where it builds fine, see: https://github.com/flathub/se.sjoerd.Graphs/pull/6

Remove aarch64 from workflow

---

src/canvas.py

Ticks on the right- and top axes were not rendered if those axes were unused. The goal is that it should be possible to have ticks on all sides, even for a regular plot with only one line.
This should fix that.

Fix ticks settings

---

src/edit_item.py
src/graphs.py

Sets the limits when
- Deleting an item
- Changing an item (e.g. when changing the axis of one item)
The reason behind this is in the first case, if I have one item with axes going from 0 to 12, and another with the limit going from 0 to 4, and then delete that first axis. Then it should reset the limits to fit the graphs that are left instead of keeping it from 0 to 12.
In the second case, the use case if if I change the axis of one of the items. So if I set the x-axis for the top item to "top", then it should set the limits so that it fits nicely for both graphs.

Set limits automatically on more occasions

---

meson.build
src/canvas.py
src/preferences.py
src/utilities.py

Gets the fail safe style from template instead of using the first available option. The reason for this is that this ensures that the dark style will be loaded in dark mode, and the light style will be loaded in light mode. And the template should always, always work. Also avoids unexpected theming if the top style is something custom that does not fit with the general style of the UI.
When people upgrade to version 1.5, the old style will no longer work so this exception will be triggered. By default it selects the top style in the current main branch, which is adwaita-dark. Giving a weird experience for people using light theme. Hard-coding adwaita will have the same issue, but for people using dark theme. This PR solves this.

Get failsafe style from template

---

data/styles/adwaita-dark.mplstyle
data/styles/adwaita.mplstyle
data/styles/bmh.mplstyle
data/styles/classic.mplstyle
data/styles/dark-background.mplstyle
data/styles/fivethirtyeight.mplstyle
data/styles/ggplot.mplstyle
data/styles/grayscale.mplstyle
data/styles/seaborn-bright.mplstyle
data/styles/seaborn-colorblind.mplstyle
data/styles/seaborn-dark-palette.mplstyle
data/styles/seaborn-dark.mplstyle
data/styles/seaborn-darkgrid.mplstyle
data/styles/seaborn-deep.mplstyle
data/styles/seaborn-muted.mplstyle
data/styles/seaborn-notebook.mplstyle
data/styles/seaborn-paper.mplstyle
data/styles/seaborn-pastel.mplstyle
data/styles/seaborn-poster.mplstyle
data/styles/seaborn-talk.mplstyle
data/styles/seaborn-ticks.mplstyle
data/styles/seaborn-white.mplstyle
data/styles/seaborn-whitegrid.mplstyle
data/styles/seaborn.mplstyle
data/styles/solarized-light.mplstyle
data/styles/tableau-colorblind10.mplstyle
src/plot_styles.py

- apply textcolor for tick.labelcolor. This allows having the ticks in a different color than their labels
- Use hex notation for grayscale color cycle
- Set patch color as first line color (all styles already behave this way)
- Tweak default adwaita color cycle

Small changes

---

src/graphs.py

This fixes a bug where Graphs would crash when changing the order of an item (with drag and drop) just after deleting an item.
The error otherwise happens without error output or warning, kinda drove me crazy for while hunting the bug down. Wasn't even sure what triggered it, just noticed it crashed sometimes.

Properly remove item from item_menu when deleting an item

---

data/config.json
data/ui/export_figure.blp
data/ui/preferences.blp
src/export_figure.py
src/preferences.py

Adds the option to set the dpi (dots per inch) for a figure when exporting, can be a relevant setting for raster images (non-svg).
Works quite well for me. Have set the maximum setting to 999 dpi, but perhaps it should have no maximum at all.

Add dpi option in figure export

---

data/config.json
data/ui/preferences.blp
src/clipboard.py
src/edit_item.py
src/graphs.py
src/item.py
src/item_box.py
src/main.py
src/operations.py
src/preferences.py
src/ui.py

Reworks the clipboard as discussed in issue #201.
Doesn't (yet) set the datadict as it's own class, but that could be a seperate PR if we were to implement this.
Also reworks the item menu as discussed, as that was needed to get the behaviour right.
Actually, this code is simpler than the previous implementation and works quite well. It correctly handles all actions, including deletions and everything. And you can even redo/undo all the way to an empty slate and back.

Rework clipboard

---

data/ui/plot_styles.blp
data/ui/style_box.blp
src/plot_styles.py

- Adds a shortcut button that allows to set the style that is being edited as custom style.
I was a bit unsure about the exact behaviour and what would be the most intuitive, but it seemed useful to have a shortcut here to quickly set the style from the editor as well. In the current implementation it hides the button when "System style" is set as default. So only if "Use Custom Style" is enabled, it shows this to allow for quick changing of the plot style. Pressing the switch sets the style directly to active style. Deselecting it sets  the active style to the system preferred style.
- Sets a checkmark for the currently active style in the "Plot Styles" overview, to quickly indicate which style is currently active.

Set checkmark for active style in style editor

---

data/styles/classic.mplstyle
data/ui/plot_settings.blp
data/ui/preferences.blp

Rephrases a few descriptions.
Also emphasize that preference options are default values not the current ones, to aid separating them more easily.
Just a quick fix thrown in: remove legend location from the classic style

minor linguistic tweaks

---

data/meson.build
data/styles/seaborn-ticks.mplstyle
data/styles/thesis.mplstyle

Add the style that I use for my own thesis. Basically it's without grids,  slightly longer ticks on the inside on all borders and a more "standard" like color cycle. I also use the same style as the basis for academic articles.
Felt to me that a style like this was missing somewhat, and for me personally it's convenient to ship these as well.

Add new "thesis" style

---

data/config.json
data/ui/preferences.blp
src/plot_settings.py
src/preferences.py

Respects the set color cycle when changing plot styles in plot_settings, I think that can have a pretty useful usecase. Especially if you have prepared a specific color cycle for specific purposes and want to change everything. 
It doesn't override the set colors if the plot style is not changed, only when the plot style is changed. Either to a different custom plot style, or when changing back to the system style.
[Screencast from 2023-04-14 11-12-43.webm](https://user-images.githubusercontent.com/68477016/232009052-0d0db8db-8d06-4804-af39-81960a9e100f.webm)

Respect style's line settings when applying custom style

---

data/meson.build
data/se.sjoerd.Graphs.gresource.xml
data/ui/add_style.blp
data/ui/plot_styles.blp
data/ui/style_box.blp
data/ui/transform_window.blp
src/actions.py
src/plot_styles.py

Instead of having a copy button on each style row, this adds one single "add style" button that pops up a dialog. It then gives a dropdown with a choice which style to base the new one on, and a field for the name of the new style. The name is automatically filled in based on the template the user chooses, but can be changed manually of course .
Other than this, there's not really something I really want in the upcoming release. Except for a warning dialog when deleting styles ("This will delete {style name}, are you sure") and for resetting the styles to the default settings, as those actions are destructive. See PR #229.

Add dedicated "add style" button

---

src/operations.py
src/plot_settings.py

In the current release version, if line settings (colors, thickness etc) are changed upon a style change, this event is not added to the clipboard. If the user then undoes directly after changing the style, all lines are reset to the old color cycle and the information about the new color cycle is "lost", which is annoying. 
This PR fixes this by adding the style change to the clipboard, this way the new color cycle (and also line thickness etc..) is not lost upon an undo action immediately after a style change, see second video.
Before:
[Screencast from 2023-04-17 13-43-39.webm](https://user-images.githubusercontent.com/68477016/232475423-4812ab58-c8fb-4864-b9be-aab71cb8ac5a.webm)
After this PR:
[Screencast from 2023-04-17 13-49-32.webm](https://user-images.githubusercontent.com/68477016/ …

Add style change to clipboard

---

data/se.sjoerd.Graphs.appdata.xml.in.in
data/ui/window.blp
meson.build
src/actions.py
src/add_equation.py

Some bug fixes, one of them being major:
- The add equation window was broken, not sure when this happened but this fixes this!
- The canvas zoom was indeed broken on extremely specific scenarios that I still cannot trace down to specific scenarios. But it has something to do with the old state not being properly stored when doing a bunch of transformations. See attached screencast. This PR binds the "Restore View" button directly to the own graphs.reload() function. I haven't been able to replicate this bugged behaviour in this new PR.
@cmkohnen Given the broken "add equation" functionality being quite severe of an issue, I am planning to push this as an "unscheduled" hotfix update as soon this is merged.  If you've got any specific bug fixes or such we can include that but I am planning …

Hotfix update

---

data/se.sjoerd.Graphs.appdata.xml.in.in
src/canvas.py
src/edit_item.py
src/file_io.py
src/graphs.py
src/item_box.py
src/plot_settings.py
src/plot_styles.py
src/plotting_tools.py
src/rename.py
src/ui.py

This adds the ability to keep the old limits after reloading a graph. In the current main branch, when switching to dark mode for instance, the limits are reset. The same is true when reordering lines to put one in front. This has annoyed me at some occasions.
This adds the optional argument reset_limits to the graphs.reload function (true by default). If this is set to false, the old limits are applied again after reloading.
In this PR, this new function is used to make the canvas resets way less aggressive. This way the old limits are kept when changing styles, line properties, plot settings etc..

Reset axes limit less agressively

---

data/ui/add_data_advanced.blp
data/ui/add_style.blp
data/ui/edit_item.blp
data/ui/export_figure.blp
data/ui/plot_settings.blp
data/ui/plot_styles.blp
data/ui/preferences.blp
data/ui/transform_window.blp
po/de.po
po/fr.po
po/graphs.pot
src/add_data_advanced.py
src/edit_item.py
src/export_figure.py
src/misc.py
src/plot_settings.py
src/plot_styles.py
src/preferences.py
src/utilities.py

Allows choosers to be translatable.
A few technical changes:
- Populating a chooser now creates a new model (removed option for keeping old ones as it wasn't used)
- Choosers need to be defined in code for set_chooser and get_selected_chooser_item (new function) to work properly
- When populating a chooser provide translatable values, querying and setting via afore mentioned values is done via the english strings
- Removed empty_chooser as it wasn't used
- Removed get_chooser_list (substituted via chooser.untranslated_items call)
All text should now be translatable, if not I'll consider it a bug.
Fixes https://github.com/Sjoerd1993/Graphs/issues/232 properly.

make choosers translatable

---

meson.build
src/meson.build

Install using the python meson module. This defaults to the pythons site_packages directory. This is more inline with what most projects do. This also allows to use the python.bytecompile option once meson 1.2 is available for the flatpak buildchain, improving startuptime app.

install to python site packages

---

src/export_figure.py

The export button was broken, as _ was an argument in the on_accept function it clashed with the new translation string variable. It's been bugging me for a while. but didn't have the time to take a look at it.
This should fix this issue.

Fix export button

---

src/canvas.py
src/file_io.py
src/graphs.py
src/plot_styles.py
src/ui.py
tox.ini

- Small fixes
- Port opening and saving projects to GFile
- Remove confirm dialog in plot styles editor in favour of the actual trashcan
Exporting to two-column files will be a bit trickier. We'll have to create a temporary file which can be accessed via "normal" python methods, since numpy only accepts a filename or pathlike instead of a ioclass for files (the latter being the proper way to my knowledge). This file can than be moved to the location the user specified. This should still work with all locations we can get a GFile from. Will put that in the next pr however, just a heads up what is needed for that

more refactors

---

src/plot_settings.py

This adds two minor changes/fixes to Plot settings:
- Put plot styles in alphabetical order in the Plot settings dropdown menu
- When a style has been changed, the sidebar menu is reloaded, such that the colours are updated accordingly.

Fix plot settings

---

src/edit_item.py
src/utilities.py

In the current build (as well as with the latest stable Flatpak build), the Edit Item window crashes when the name of an item is changed, and then a new item is loaded.
This bug is triggered somewhere on the repopulation on the chooser, but I have not been able to pin down the exact cause of this. As I'm pressed on time, I decided to put this current workaround (which is to use the old implementation) here as a WIP PR, but I think it's probably for the better if we try and fix the current repopulation function instead.
Not sure when I have time to look closely into that behaviour, but at the latest early next week (PhD defense is on Friday, that is my last big deadline for a while).
There are a few bugs that got introduced when we added localization support. Most of them are fixed in the …

Fix crash with chooser change

---

src/actions.py

In the latest build, only the top item gets deleted when pressing the delete button. The reason for this is that it loops through the dictionary itself in actions.py, changing the dictionary size upon iteration which is not allowed. This solves this by looping through the selected keys instead like in previous releases.

Fix deleting multiple items

---

src/plot_styles.py

The conditional for checking if a custom style was used was reversed. The result was that all styles got a checkmark when a custom style was selected. This fixes that.

Fix plotstyle checkmark

---

src/plot_styles.py

The fix in PR #315 made everything work great when a custom style was selected, but introduced a bug where all plot styles got a check mark when the system prefered style were used. This fixes it such that it works for all.
I've also started to take a look into the slight color difference between the plot and the sidebar in the dark mode of the Snap version. You can retrieve the system theme color quite well code-wise using the following pieces of code:
```
styles = application.main_window.get_style_context()
rgba = styles.lookup_color('theme_bg_color')[1]
rgba_tuple = (round(rgba.red*255), round(rgba.green*255), round(rgba.blue*255), round(rgba.alpha*255))
color_hex = '#{:02x}{:02x}{:02x}'.format(*rgba_tuple)
```
And then you can just set the facecolor of the figure (not the axes) to …

Fix plot style checkmarks

---

src/plotting_tools.py
src/utilities.py

Remove the rounding of the limits based on significant digits. This was originally introduced to gaurantee "Clean" figures when looking at the axis limits in the plot settings.
But I have realized this causes more issues than it's worth. Specifically, this causes issue when working with data sets with large numbers, where the minimum and maximum value are relatively close  to eachother. As an example, if the X-axis goes from 2000 to 2023, then this rounds this all to three significant digits. Meaning it will round this to 2E3 (so 2000) and 2.02E3 (so 2020), cutting off the last 3 values from the X-axis. These are not even obscure cases, as this is just with years.
When working with even bigger ranges (12312331 and 12312339 for instance), it will make the entire limits just unusable …

Remove sig fig roundings

---

src/main.py

Drops the keyboard shortcuts that are shift+letter. 
The reason behind this, is because these shortcuts get triggered while creating axes labels as well. Making it currently impossible to write an axis label with a capital S for intance. The effected commands do have an alternative shortcut in the F-keys.
An alternative solution be to disable all shortcuts when an EntryRow is selected, but I am not sure if that's possible. That would be the nicest solution though I think.
In the same note, we should consider removing the following shortcuts as well, as they do interfere with writing labels/titles as well:
- Delete (deletes the selected items, currently while renaming something. If I press delete to remove the character in front of the cursor, it deletes the selected items instead of the …

Drop shift+letter shortcuts

---

data/se.sjoerd.Graphs.appdata.xml.in.in

There's a slight syntax error in the changelist, making the latest changelist not show up in GNOME Software (at least for the latest release). Fixing it would require tagging and pushing an entire new release and it doesn't really change the user experience, so that may not be worth to fix it in this version (the info is still there in whats new also), but it's good to fix it anyway so that it will show up in the history after next patch.
I guess this syntax error is why the changelist for 1.6.1 doesn't show up at least... I tried validating the xml file and couldn't detect any more errors.

Fix appdata changelist

---

data/se.sjoerd.Graphs.appdata.xml.in.in
data/whats_new
src/file_io.py

Currently when importing columns, it only loads if the iteration index is larger than the amount of rows to be skipped. At the first iteration, the index is zero. Meaning that it skips the first iteration when skip_rows = 0. So basically, the first data point is skipped currently.
It should of course compare to skip_rows >= index.

Fix skip rows

---

src/plotting_tools.py

Because these parts of the axes always are turned off anyway (line 84 and down), it makes no sense turning them visible first. So these lines can be removed without losing anything

Remove redundant lines of codes

---

src/canvas.py

When the top axis limits got set, it tried to set the limits to the Y-axis, but that should be x-axis of course. This lead to broken scaling when e.g. reloading a graph (for instance when changing plot style).
This fixes that bug.

Fix top axis limits

---

src/canvas.py
src/graphs.py

When multiple axes are used, the ticks from each axes are overlapping. See screenshot:
This is never something you want in an actual graph. Basically, the change in this PR is that for a specific axis, opposite ticks are not plotted now when the opposite axis is already in use by a data set. This does mean that the condition for each axis needs to be checked separately with slightly different conditions, so I could not get it to work in a single loop. But it's readable enough. See screenshot for the same data after this PR:

Fix overlapping ticks

---

.github/workflows/main.yml

Currently workflows are run on every push and every pr. This changes that to only run for pushes directly to main and any pr that is targeted to main. This eliminates duplicate workflows, when pushing to a branch, that is already a pr

Limit workflow runs

---

src/item_box.py

- Set the transparency in the color button as well
- Load the transparency correctly when choosing a new color. In the current main branch, when the color button is clicked, the actively selected colour is the non-transparent one. So pressing OK without doing any changes will make the item lose its transparency.

Minor transparency improvements

---

src/file_import.py
src/file_io.py
src/misc.py

Instead of catching every possible Error in the caller function, raise
an ImportError with a translatable message with each respective error.

Use better Error Handling.

---

src/actions.py
src/canvas.py
src/clipboard.py
src/edit_item.py
src/file_io.py
src/graphs.py
src/item_box.py
src/main.py
src/operations.py
src/plot_settings.py
src/ui.py

This refactors the clipboard into its own class. The main reasoning was that this allowed to save the associated limits for each state to the clipboard state. This way, when undoing a certain action, the axes reset also to the state that was present at the time before that action was performed.
See old behaviour here: https://github-production-user-asset-6210df.s3.amazonaws.com/68477016/247573650-9c9dbaaf-b8d3-459b-8c68-0210445b2c33.webm
And new behaviour in this PR here:
[Screencast from 2023-04-02 21-15-03.webm](https://github.com/Sjoerd1993/Graphs/assets/68477016/bbc035d5-ef6b-4310-9951-0f3858b89d8a)
Another thing in the behaviour that has changed is that when opening a project, it automatically reloads the limits that were set during the previous session. See video:
[Screencast from …

Refactor clipboard

---

meson.build
src/actions.py
src/canvas.py
src/clipboard.py
src/file_io.py
src/graphs.py
src/item_box.py
src/main.py
src/plot_settings.py
src/plotting_tools.py
src/ui.py

Reworks the clipboard as well as the view navigation. 
The clipboard is now one class, where two subclasses are used that inherit from the base class, one for the data and one for the view. This allows us to couple the view navigation to this custom clipboard instead of using the navigationtoolbar build-in. This also allows us to store the view clipboard in project files, and load the latest view upon loading in a less hacky way. 
The other thing that has been changed in behaviour, is that undo/redo now sets the views to whatever the status was on the previous/next action. Any suggestions on what exact behaviour would be preferred are always welcome :)
Also, there's some potential for further refactors into the clipboard classes eventually. There's still some duplication going on.

Rework clipboard and view navigation

---

src/plotting_tools.py

In the current main, the limits are never pushed to the plot settings after an optimize limits call.
This means for instance that the old limits will be loaded into the entry fields after going into the figure settings afterwards. When closing that dialog, the old limits will be loaded into the canvas. Also the limits wouldn't be saved into a new project file.
This PR fixes this bug.

Fix optimize limits scaling in plot settings

---

src/canvas.py

Simplifies the on_define function a bit in the Highlight class. 
Effectively does the same thing, but a bit cleaner imo and shorter.

Simplify Highlight._on_define

---

src/ui.py

Default behavior when toggling an ExpanderRow expands it.
This way, when the initial state is enabled, it gets automatically expanded as well.

expand ExpanderRows automatically

---

data/config.json
data/ui/preferences.blp
src/clipboard.py
src/preferences.py

Removes the maximum clipboard length option, and defaults to a standard limit of 75 instead. It's extremely rare for a user to actually want to change the setting.
The limit of 75 was taken as a bit of a compromise of being long enough that it should never really be a big issue, but still limited so that the amount of data stored in memory is somewhat limited. I'm happy to discuss the exact value of this limit though.

Remove clipboard length option

---

src/plot_styles.py
src/preferences.py
src/ui.py

Preferences are automatically saved, when they are updated using `update()`.
Also tweak logic behind `save_values_to_dict` to accept a list of all keys and return a dict

Refactor preferences.

---

data/meson.build
src/actions.py
src/add_equation.py
src/canvas.py
src/clipboard.py
src/edit_item.py
src/file_import.py
src/file_io.py
src/graphs.py
src/item.py
src/item_box.py
src/main.py
src/meson.build
src/migrate.py
src/misc.py
src/operations.py
src/plot_settings.py
src/plot_styles.py
src/plotting_tools.py
src/project.py
src/rename.py
src/ui.py
src/utilities.py

Closes https://github.com/Sjoerd1993/Graphs/issues/394
Use new Format for storing project files.
Refactor huge portions of the codebase to adapt new format.
Rename some item and figure_settings properties.
Old project files can still be opened. (Ones created in 1.6.1 or earlier. Clipboards are lost however (like the current implementation))

New project file format

---

src/clipboard.py
src/graphs.py
src/operations.py
src/ui.py
src/window.py

In the last PR, I found some bugs which I solved along the way, and thought it was easiest to just push those in a seperate PR. 
- Shift vertically was no longer working. This is because the term `yscale` was replaced to the much more sensible left_scale. (Using `yscale` for left the `left scale`, but `right_scale` for the right scale is a terrible idea so this was a good change. The reason for this inconsistency was simply due to historic reasons, in the very first version when this `shift_vertically` function was implemented, there was only support for a single y-scale, so back then the `y_scale` name made sense. Then I added a second y-scale, hence the `right_scale` name, but  didn't rename the left-hand scale.
Anyway, this is fixed now
- Open loading a project, the items were not …

Minor bug fixes

---

data/ui/edit_item.blp
src/edit_item.py
src/ui.py

Allows item changes to happen instantaneously.
This also gets rid of optimizing limits each time the edit item window closes, because x and y position are modified

use bindings for edit item

---

data/ui/window.blp

Open for discussion if we wanna keep it the way it is or change it.
The benefits of this are in my opinion, that buttons always stay relative to each other.
On small resolutions you'd always have to scroll but given the default resolution all elements (except translation) are visible.
On a 100% scaled 1080p monitor all items are visible without the need for a scrollbar.

Suggestion: Redesign operations

---

data/ui/window.blp

Puts the operations into cards, to create some more visual distinction between the categories in the side-panel. Slightly inspired by the way different things are categorised in e.g. GNOME Settings. Open to further suggestions.

Use cards for operations

---

data/ui/item_box.blp
src/item.py
src/item_box.py
src/utilities.py

Somewhere along the way the item labels lost their limits. This makes the side-panel expand to unreasonable widths with very long filenames. This fixes the label length again

Limit item name length

---

src/ui.py

Another tiny PR, adds a toast when data is exported succesfully just like when saving a figure. Also adds a toast when there's no data to export, so it doesn't just look like it's not reacting properly.

Add toasts to export data

---

src/canvas.py

Currently, when panning/zooming on the graph, the canvas itself steals focus. This means that shortcuts such as ctrl+z or ctrl+N and such no longer work.
There's no real reason to have a the focus on the canvas. This change makes it such that shortcuts keep working.

Stop canvas from stealing focus

---

data/ui/figure_settings.blp
data/ui/window.blp
src/main.py
src/scales.py
src/utilities.py

Adds square root scaling as fourth option. I don't have any immediate plans of adding more options here (inverted (1/x) would be an option though). But as I mentioned, I am considering adding a context-depended option for .xrdml files so it will be possible to easily toggle between angular coordinates and reciprocal space. (Something which isn't even possible with the official DataViewer software from Panalytical, which frankly is pretty bad anyway)

Add square root scaling

---

src/artist.py

Since artists require some values. These get set twice. Once during init and once during initial sync.
This changes that, so that all values get passed along during init and only updated, when the item's property updates.

Don't perform initial property sync

---

data/se.sjoerd.Graphs.gschema.xml
data/ui/figure_settings.blp
data/ui/preferences.blp
data/ui/window.blp
src/actions.py
src/canvas.py
src/operations.py
src/scales.py
src/utilities.py

Add inverse scaling to the amount of options. Needed some tweaks to get this to work correctly with panning/zooming, `select_data`, as well as with axis-dependent operations like `shift_vertically` and `optimize_limits`.
Finally, this also adds an `optimize_limits` call to scaling changes, as the scaling is often not good at all directly after changing scale, so running `optimize_limits` is often the first thing you want to do anyway.

Add inverse scaling

---

src/figure_settings.py

There's a bug in the current Figure Settings, where it always loads "Adwaita", even if another style has been set previously. This also persists when setting a different default. The cause is that `self.custom_style.set_model(Gtk.StringList.new(styles_))` resets the current `custom_style` property as well, so the previously set custom style is overloaded by adwaita.
This PR fixes this issue.

Fix custom style

---

src/canvas.py
src/scales.py
src/utilities.py

Changes the behaviour of locators on custom axes scaling, also offers some slight tweaks on the Inverse scaled limits.
The main point is that the locators (ticks) are now distributed evenly for the square root and inverted axis, leading to less awkward scaling in certain cases. For example with tons of ticks extremely close to each other. 
I am not 100% sure if an even distribution is always completely what we want. But in many cases it leads to a more readable graph. Here's the screenshot with and without the even ticks. One option is to have it as a toggle in the style sheet.

Change locator behaviour on custom axes scales

---

src/canvas.py
src/clipboard.py
src/scales.py
src/utilities.py

Uses a custom locator class instead of calling a new fixed locator each time the axis is changed. Giving a much more stable and polished experience.
I was a bit unsure whether I should use a seperate class for the inverse and square root case, but it works well enough like this.

Use custom locator class

---

src/utilities.py

Removes infinite values from the min/max limits, such that it becomes possible to plot e.g. y = 1/x from x = -3 to x = 3. It now simply takes the minimum or maximum non-infinite value.

Fix scaling with inf values

---

data/ui/add_equation_window.blp
src/scales.py

Two minor fixes, that maybe should have been their own PR.
- The label in "add equation" is in the current main branch closer to the "Name" section, while it belongs to the "Add equation" section. This puts the label closer to where it belongs
- Suppress errors with invalid values on the square root scaling. This prevents it from spitting out errors when for instance dealing with negative values. (Again this is the same behaviour as [ProPlot](https://proplot.readthedocs.io/en/latest/_modules/proplot/scale.html#InverseScale.limit_range_for_scale) uses on their custom axes. Stumbled upon that library when trying to read up on custom locators. They've got a bunch of nice ideas to take inspiration from)

Fix label in equation window and surpress square root error

---

data/ui/help_overlay.blp
data/ui/window.blp

I was looking into the [GNOME Circle criteria](https://gitlab.gnome.org/Teams/Releng/AppOrganization/-/blob/main/AppCriteria.md), where it states that [standard keyboard](https://developer.gnome.org/hig/reference/keyboard.html) shortcuts should be followed to ensure consistency with other applications. The default for preferences is Ctrl+comma, so we should probably use that.
Unfortunately ctrl+shift+comma does not work, as that triggers a `ctrl+;` in my case (ctrl+shift trigger a semicolon). A workaround would be to bind it to `ctrl+;`, but the secondary key behind the comma differs depending on the keyboard layout. (I am not sure about every single layout, but dvorak has a `<` behind the comma). So for now I bound styles to `ctrl+.`.
I bound optimize limits to `ctrl+0` as to mimic the …

Update shortcuts to follow GNOME Circle

---

data/meson.build
src/application.vala
src/clipboard.py
src/clipboard.vala
src/data.py
src/data.vala
src/figure_settings.vala
src/file_io.py
src/main.py
src/meson.build
src/ui.py

It took me literally days to figure out, why the vala compiler wouldn't work with composite templates. The solution was that he was looking for .ui files in data/ui where only .blp files (not yet compiled) exist. The solution was to copy the gresource xml into the build directory, so the vala compiler would have access to the compiled ui files.
This includes exactly that plus moving the applications properties to vala. This also includes the proof of concept on how to handle implementations written in python inside vala code. We simply define interfaces in vala, with functions we like to access, and add them as inheritance to the python class. This way we'd have to change nothing on the python side while still being able to access functions in vala code.
Another solution, like the one …

move application properties to vala and update build system

---

data/ui/window.blp
src/actions.py
src/main.py

See title. When scaling is changed through the view menu, the focus is changed to the view menu. Making it impossible to use shortcuts. This fixes this.

Prevent view menu from stealing focus

---

src/main.py

Very minor PR, but since migrating the last application class to Vala, the import of Adw and GObject has become redundant. Flake8 picked this up locally, didn't see anything failing here for some reason though.

Remove redundant imports

---

src/main.py
src/migrate.py

Fixes the migration. I was comparing some behaviours with the current stable branch, and when hopping back I got an error.
There were two issues:
1 - The migration was given `self` as argument, instead of the settings
2 - When going through the categories, `settings` was getting overwritten, making it such that it cannot find the settings anymore after one loop.

Fig migration

---

src/data.py

The reason for reverting to an item menu reload after changing items, is that the current behaviour is extremely buggy. See screencast:
[Screencast from 2023-09-08 10-12-01.webm](https://github.com/Sjoerd1993/Graphs/assets/68477016/7a4d10c1-0e59-4988-8ccc-a44cfe8aa90e)

Fix item change implementation

---

src/file_io.py
src/utilities.py

Fixes column import, which was broken if the first line was a blank line. Also makes it such that a single column file with a single header, sets the header at the y-axis and the x-axis. Finally, the headers were a bit broken overall. This should all work OK now.

Fix column import

---

src/clipboard.py
src/edit_item.py
src/item_box.py

I noticed a warning that the uuid cannot be set when going into the item edit window. So I went through the code to check where key was still used instead of the uuid attribute, and found a few instances.
The reason for the warning by the way was because the IGNORELIST when binding the values to the objects in the window, still contained key instead of the uuid. But this PR includes a few other places as well where key was still used.

Complete transition from key to uuid

---

src/data.py
src/ui.py
src/utilities.py

Remove get_next_color() from utilities. When adding a number of items, this used to loop quite often. Also during reset. This changes that to use the already existing loop structures

remove get_next_color()

---

data/ui/import.blp

This was quicker than I anticipated, as they were already converted to enums during migration to gschema settings. 
Fixes #487

Fix decimal seperator formatting

---

src/canvas.py

In the current main branch, the legend is always chosen on the "top" axis, which is top_right. However, this means that it doesn't properly "hide" if a line is in front of the legend. Which is not ideal. This PR fixes this, so that the legend is put on the top axis that happens to have a line on it instead.

Improve legend positions

---

src/data.py

- Make data.items notify explicitely. This was already kind of the case before, now it is just a bit more verbose.
- Only update figure_settings on project load, if the value is different
- Use the can_view_{back/forward} property to check if respective actions are possible.
- exit history functions earlier if executing isn't possible

small improvements

---

data/ui/figure_settings.blp
src/figure_settings.py

In the current main branch there's the following bug: 
When a custom style is chosen, and the lines don't have the same color as default, and then figure settings is opened, then the colors are over-ridden by the default values of the chosen stylesheet. The reason for this, is that when the dropdown menu is created in the code, the selected index is by default 0 (adwaita). Then when the correct index of the current stylesheet is set in the next line, the code recognizes that as a changed style. So the line properties are taken from that new stylesheet. (So same bug will be there for non-default line widths etc..)
Of course the lines shouldn't all revert to default values when just opening the figure settings. This issue can be mitigated by simply connecting this signal *after* setting the …

Fix figure settings style change

---

data/se.sjoerd.Graphs.gschema.xml
src/application.py
src/styles.py

Sets the Yaru system theme for the Snap package. Feel free with suggestions for other implementations. The logic here is that both the Snap and the Flatpak set some fingerprints in the environment variables (most noticable SNAP for the Snap package, the Flatpak can be identified  by the presence of FLATPAK_ID). 
Then for the Snap package, where the system theme is applied instead of libadwaita it checks what the current Gtk theme is. If this is set to anything that starts with Yaru (so also the Yaru variants), then Yaru is set as the preferred system theme. Otherwise it revers to adwaita, our preferred theme we target for. The reasoning for that second line where it reverts to adwaita, is that the settings are saved. So if the yaru theme is set in the Snap, and you then switch themes back …

Set Yaru theme for snap package

---

data/ui/style_window.blp
src/data.py
src/figure_settings.py
src/styles.py
src/utilities.py

Styles are now in two groups: user styles and system styles. For the user this is mostly transparent. In Figure settings one can always choose any style to be used. In the styles window however just user styles can be added.
This also splits off duplicated logic for appending " (n)" at strings to be added as well as improving this functionality so that e. g. "adwaita (1)" becomes "adwaita (2)" instead of "adwaita (1) (1)"
Migration (deletion) for user styles, that are identical to the system ones will be another pr, but can be included here if required.

Rework style logic

---

src/application.py
src/application.vala
src/styles.py

After trying out the Snap package, I found two errors:
- When the Snap package is ran (which I found is detected correctly, so that's good), and Yaru is not set as theme, `system_stylename` was never declared. This PR fixes this by setting adwaita first as default, and then overriding this for the Snap package in case Yaru is set as the theme
- For some reason, when getting the system theme from the update method in `styles.py`, it always returns `Adwaita-empty`. Not the actual theme. This is fixed by setting the theme upon init as property of the application. Ideally, I'd like it to run a `Gtk.Settings.get_default().get_property("gtk-theme-name")` when getting this attribute. But I haven't succeeded in getting this to work from the Vala class. Either way when I try to import Gtk there, …

Fix yaru theme

---

src/application.py
src/application.vala
src/figure_settings.py
src/interfaces.vala
src/migrate.py
src/styles.py
src/ui.py

Styles are now managed using a StyleManager helper class. This keeps track of any changes that might happen which would require styles to be updated and inherently the canvas to be reloaded. Also instead of iterating over the styles directory every time a list of styles is requested (which can happen quite often and sometimes get_system_styles gets called twice to check if the file is correctly named), a reference is kept, which automatically updates when something in said directory updates.
This is also a stepping stone for some ideas suggested in https://github.com/Sjoerd1993/Graphs/issues/529 as this would make implementing e. g. previews a lot more efficient.

Refactor style logic

---

python-dependencies.json
snap/snapcraft.yaml
src/file_io.py
src/migrate.py
src/styles.py
src/utilities.py

Generates a preview image (svg) for user styles, whenever a style is added.
For example:
Very much subject to change, this is just for implementing the functionality.
Also this introduces a (small) new dependency for manipulating svg images. This one was chosen, because we can generate an image directly from a mpl figure and export (using etree) as binary sequence allowing to integrate perfectly with GFile.
In future we might want to discuss, if these should be stored as files or in memory (each preview is only a couple of kilobytes) to reduce fs overhead.

Generate previews for user styles.

---

data/ui/preferences.blp

As suggested in the GNOME Circle feedback, disables the search in preferences.

Disable search in preferences

---

data/ui/figure_settings.blp
src/figure_settings.py

The current main branch has a weird spacing below the axes limits in Figure Settings. This is due to the entries themselves being hidden, but the box where they are in is not hidden. An empty box still takes some spacing, hence the spacing in the axes limits being wrong.
This PR fixes this, by hiding the boxes themselves instead of the entries. So the spacing is correct. 
Furhermore, the entire group with the limits is put into it's own box. This is so that a single `spacing` attribute can be set for all these widgets. This is necessary, as the current spacing set individually in each box means that there's a bottom-spacing on the lowest entry. (Unless that entry happens to be the limits for the top axis, but in 95% of the cases one works with left and bottom). Grouping these in a box, …

Improve spacing in figure setting limits category

---

data/ui/figure_settings.blp
src/figure_settings.py

Fixes the toast in the figure settings, so it shows some feedback when updating the defaults. 
The changelog is misleadingly large, as the blp just adds one more layer with the toast overlay being the new parent of the navigation stack.

Fix toast overlay in figure settings

---

data/ui/window.blp
src/actions.py
src/window.vala

The current behaviour in `operations`, the action identifier is retrieved from the button label. This breaks down with localised versions where these strings have been translated. I just stumbled upon this, as I just happened to have Graphs set to Dutch from testing localization earlier.
In this PR, the buttons have been given a label as identifier, and the Variant string is retrieved from that instead. Making these Id's consistent for different locals.

Fix localised actions

---

data/se.sjoerd.Graphs.appdata.xml.in.in

- The release description must be put inside a `description` tag. Tested with the following command:
```appstreamcli validate --explain data/se.sjoerd.Graphs.appdata.xml.in.in```
- These URLs are visible on Flathub and GNOME Software.

data: Update appdata

---

data/meson.build
data/se.sjoerd.Graphs.appdata.xml.in.in

Sets the appdata test to be a bit stricter, so it also fails the PR if a date in the future is set for instance or when appdata styling is not correct (e.g. too long caption names). This would have prevented the solved bug in PR #554 
Had to make some slight changes to the release notes and screenshot captions to get it to pass. URL Lookups are not allowed within the GNOME Builder Sandbox, so this particular test doesn't run well from GNOME Builder. It does test everything properly, but it will always give the following errors as well:
```
Validate appstream file
/var/home/sjoerd/Projects/Graphs/_build/data/se.sjoerd.Graphs.appdata.xml: 
(appstream-util:2): As-WARNING **: 07:35:13.067: failed to lookup proxy for https://raw.githubusercontent.com/Sjoerd1993/Graphs/main/data/screenshots/sin_ …
```

Stricter appdata check

---

src/operations.py

The line `index = 1 if index == 0 > 1 else index` leads to an index error later on in cases when there's only one item loaded. This condition should only be triggered if there's at least two items.

Fix shift with single item

---

data/se.sjoerd.Graphs.gschema.xml
data/ui/preferences.blp

Adds subtitles to the first two options in the preferences, basically due to comments from @bertob that the options were a bit unclear. https://gitlab.gnome.org/Teams/Circle/-/issues/185
Perhaps the last two also need some slight explanation. They seemed somewhat clear to me (at least "Hide unselected items" seemed OK to me personally), but to a new user they may be a bit unclear at first glance. So I'm open to suggestions to clarify these options somewhat.

Add subtitles in preferences

---

data/ui/figure_settings.blp
src/export_figure.py
src/figure_settings.py
src/file_io.py
src/item.py
src/migrate.py
src/misc.vala
src/parse_file.py
src/style_io.py
src/styles.py
src/ui.py
src/utilities.py

- Display used style in Figure Settings initial view and use correct design pattern (Inspired by gnome-control-center)
- Fix startup with custom style (in user directory)
- Don't inject an attribute into RcParams
- Move Style class to vala and use proper getters and setters
- Annotate all functions in style_manager
- Fix parsing error triggering not found message
- Check for ubuntu only on init to save resources
- Move preview generation to style_io and use tmpfile instead of one in cache dir
- Fix selected style not updating in some cases
- Use classmethod instead of staticmethod for items
- Implement file-like-wrapper to avoid in-memory buffers
- Progressively parse columns and styles
- fix migration issues
- Use Context manager for file handling

misc improvements

---

data/se.sjoerd.Graphs.gschema.xml
data/ui/preferences.blp
src/data.py
src/edit_item.py
src/item.py
src/item_box.py
src/migrate.py
src/operations.py
src/preferences.vala
src/styles.py

As discussed in #563, remove the preference option in regards to item override.
For visual reasons this also removes the grouping in the preferences, as there are only three items now.
Creating items has also been made more modular using some of the logic necessary to handle reset() properly.
Also revert usage of `__gtype_name__` to check for instances of Item. This allows to have future items that inherit from e. g. DataItem.

rework resetting item properties on style change

---

src/canvas.py

I found the root issue behind bug #567. The main issue is in line 122 in `canvas.py`:
```
dict.update(pyplot.rcParams, orig_params)  # revert rcParams
```
The `orig_params` dictionary always holds `xtick.visible` and `ytick.visible` equal to `False`, as this is just simply the rcparams in the matplotlib defaults. For some reason, when setting `rcparams` back to the defaults, it copies the minor tick settings back to these defaults as well. I am a bit stumped about why this does not happen for e.g. `ytick.direction` though. If I set `        pyplot.rcParams["ytick.minor.visible"] = True` at the end of the init function, then the minor ticks on the y axis are turned on. Even though only rcParams have been updated, while these are not even used directly. From what I can tell, the …

Do not revert rcparams

---

data/styles/adwaita-dark.mplstyle
data/styles/adwaita.mplstyle

Slightly tweak the colors of the adwaita stylesheet for the Graphs. See below for previews:

tweak style parameters

---

data/ui/curve_fitting.blp
data/ui/fitting_parameters.blp
src/curve_fitting.py
src/curve_fitting.vala

Redesigns the curve fitting dialog, addresses [the points in the GNOME Circle feedback](https://gitlab.gnome.org/Teams/Circle/-/issues/185), and makes the dialog more responsive for different screen sizes.
Before:
After:

Redesign curve fitting dialog

---

data/styles/yaru-dark.mplstyle
data/styles/yaru.mplstyle

Updates the Yaru style to be in line with the recent changes in the Adwaita styling. That is, softer colors for the grids and axes, and with identical axes `edgecolor` and `facecolor`.

Update yaru style

---

src/curve_fitting.py

See title. The exported list of xdata in the curve fitting tool is saved as a numpy list. This leads to some clashes with some operations, where we expect a regular list. Making it impossible to perform operations on data that has been added using the "Add fit to data" button.
This simply forces these results to be a list. Solving above issue.

Save curve fit result as list

---

src/style_io.py

Makes some slight tweaks/fixes to the generated previews:
- Reduces the amount of data points so that distinct markers can be differentiated from each other
- Adds a spline for the bottom and left axes. These are currently missing if draw frame is turned off
- Removes the ticks from the top and right axes. Currently ticks are shown there, even if there's no spline. (When frame is off, and "ticks on right axes" or "ticks on top axes" are on)

Improve style preview

---

src/data.py
src/item.py

Moves the `to_dict()` function to be a method of any items, now that the mixin for other stuff exists.

move to_dict to mixin

---

data/meson.build
data/se.sjoerd.Graphs.gresource.xml
data/se.sjoerd.Graphs.gschema.xml
data/ui/smoothen_settings.blp
data/ui/window.blp
src/actions.py
src/application.py
src/meson.build
src/operations.py
src/smoothen_settings.vala
src/utilities.vala

This implements extra options for smoothening. This includes a new filter technique, the Savitzky–Golay filter which allows to do some pretty cool filtering. See example in the screencast, where I'm filtering a noisy sine wave. The original sine wave is has an amplitude of one, with some `np.random` noise added to it. As you can see, with a moving average you won't really get a smooth sine back, but the Savitzky–Golay draws a polynomial using defined window ranges and comes with this much nicer graph.
This all works now, but it probably needs some cleaning and it will not pass linting likely. I'm already running late though, so I wanted to put this up before I start on work.
[Screencast from 2023-11-17 08-35-11.webm](https://github.com/Sjoerd1993/Graphs/assets/68477016/f82b8fbc-8491-452a-8 …

Implement smoothen options

---

data/ui/edit_item.blp
src/edit_item.py

Adopts the same logic in the style editor, where the marker size and linewidth are hidden when these items are turned off.

hide linewidth and markersize

---

data/styles/fivethirtyeight.mplstyle
src/styles.py

1 - Sets the FiveThirtyEight label paddings to 7 like most other plots, to remove the overlap at these labels
2 - Clears rcParams to the defaults upon style change. This is because parameters that are not in the defaults do not get reset, so by setting rcParams to default first it is assured that all parameters are as expected. This fixes the bug that is visible in the followign video:
[Skärminspelning från 2023-11-20 15-58-00.webm](https://github.com/Sjoerd1993/Graphs/assets/68477016/a10a4892-8756-4ece-8325-28b4aff77b64)
As can been seen, the fonts get permanently smaller after having had "Classic" style open. This can only be fixed by a complete restart of Graphs.

Style fixes

---

src/styles.py
src/utilities.py

Sets the color choice of the preview icon for the style on the axes facecolor, instead of the overall brightness. This because the pencil overlaps with the axes facecolor. Currently if the axes facecolor is white, and the figure facecolor is black, the pencil becomes white rendering it invisible. Looking at the axes facecolor, where the pencil is actually located, will be less prone to such issues.
See the dark background (1) style for comparison.
Before:
After:

Set preview icon on axes facecolor

---

data/ui/figure_settings.blp
data/ui/window.blp

As per the GNOME Circle feedback: https://gitlab.gnome.org/Teams/Circle/-/issues/185
- Sets the sidebar in an Adw.Toolbar
- Sets the "Set as default button" in Figure Settings to natural width, increases margins for this button.

UI changes

---

src/misc.vala
src/styles.py

Currently the brightness of a style is calculated when the Figure settings are opened. This requires parsing the file and introduces percieved delay. This changes that functionality so that the luminance is calculated when the preview is generated.

calculate luminance on preview generation

---

src/item_box.py

The reason the ItemBox got the name property was to be able to shorten it. Using ellipsize instead makes this redundant and unnecessary.

remove proxy

---

src/item_box.py
src/ui.py

Improves drag and drop visuals. Unfortunately I'm a bit stuck trying to get the blue frame around the widget during the entire dragging phase.
[Skärminspelning från 2023-11-21 21-24-54.webm](https://github.com/Sjoerd1993/Graphs/assets/68477016/7c88dc44-e904-43ab-94e2-6ad25badb77d)

Improve drag and drop

---

data/ui/item_box.blp
src/item_box.py

Uses ellipsize to shorten labels. This ensures a consistent label length ("A" and "1" don't have the same character length so capping the characters leads to different max lengths), and also makes sure that all available space is actually used.

Shorten label using ellipsize

---

data/se.sjoerd.Graphs.desktop.in.in

Adds keywords to the .desktop` file. This should give Graphs tags at Flathub (see [this application](https://flathub.org/apps/io.github.veusz.Veusz) for example), but also means that it will pop up when searching for the keywords in e.g. GNOME Software or Flathub, making it more discoverable.
Open to suggestions about adding or removing keywords.

Add keywords

---

src/data.py

Currently performing an undo after deleting an item is a bit buggy. I think I found the issue, which comes down to the offset that's missing in `self.change_position(change[0], len(self))` (A single item will show a length of 1, but that will of course still be positioned at index 0).

Fix undo delete action

---

src/scales.py

Closes issue #486 
Logic is a bit ugly still, but it works well and relatively efficient. Will clean this up before marking this as ready for review.
If there's fewer than four ticks, it halves the spacing between the ticks until there's at least four ticks again.
If there's more than 9 ticks. It will try with a spacing of 2 pi. If that's not enough, it will try with a spacing of 5 pi. Otherwise, it will increase that spacing with 5 pi until there's fewer than 9 ticks again.
The work to do is in making this a bit more clean. Also in the case of halving the amount of ticks, I'll do this with a calculation like for the case with more than 9 ticks:
```
if num_ticks > 20:
distance += (5*numpy.pi) * (int(num_ticks/50)) - numpy.pi
num_ticks = int((vmax-vmin) / distance)
```
The above needs …

Fix radian scales

---

src/application.py
src/application.vala
src/canvas.py

Implements drag to pan with two-fingers on the touchpad, or using horizontal/vertical scrolls. 
To zoom in with the scroll wheel a ctrl modifier now has to be used, resulting in the same behaviour as applications like Inkscape and LibreOffice.
Closes #595 
Still WIP, as this needs to be cleaned up and will probably not pass linting, haven't even checked the linter locally but thought I'd put this up before I call it a day. Also there's some slight bugs in the inverse scale at least, and need to tweak the values a bit.

Implement panning support

---

src/canvas.py

- Enables middle-click to pan, regardless of current mode of operation. This mimics the same behaviour as other tools such as Inkscape, and is thus more consistent with regard to the new gestures
- Accelerates the panning values with a factor of 10 when a mouse wheel is used to pan, as it was way too slow now with the mouse wheel.
Open to suggestions with regard to the scrolling speed, as well as the implementation of middle click panning and its merits. The implementation itself very effective, but not the most beautiful code I've ever seen to just overwrite the event button and mode when a middle click is detected. 
Middle click to pan is not exactly essential, as there's a whole dedicated mode to it, so I'm fine with leaving that out. But it felt like an intuitive way to pan the canvas …

Panning tweaks

---

src/data.py

When opening a new project, the action buttons in the sidebar did not become active. Turns out it's not notifying the `items-selected` signal, this PR fixes that.

Fix project item selected signal

---

data/se.sjoerd.Graphs.gschema.xml
data/ui/import.blp
src/file_import.py
src/migrate.py
src/misc.py
src/parse_file.py

Adds a dropdown menu for the delimiter choices with more understandable options. When a custom delimiter is chosen, an entry row is shown where the delimiter can be specified manually. Closes issue #627

Use delimiter dropdown

---

src/figure_settings.vala
src/styles.py

Since styles now use the style name instead of the filename, the adwaita style should be loaded as "Adwaita". It is for this reason that you see a "adwaita does not exist, loading prefered style" right now when opening a new project. This fixes that by properly setting the default style to Adwaita instead of adwaita.

Fix adwaita capitalization

---

data/style.css

Alternative to #635 
Have been working on this for a few days now but never got it to work correctly until now.
Makes the focus-ring appear on the picture only

fix focus ring

---

src/canvas.py

Currently when "hide unselected" is turned on, a handler is connected to them that redraws the canvas when the item is selected. This happens however on every single instance the canvas is redrawn, and thus a second handler is connected to the item when the item is selected a second time, and this keeps adding up. Eventually so many signals are sent, that selecting/deselecting an item becomes unusable. See screencast.
[Skärminspelning från 2023-12-08 21-29-01.webm](https://github.com/Sjoerd1993/Graphs/assets/68477016/c263402a-765e-4745-a83c-c7328e9bab5b)
This PR fixes this. It's not my favourite thing in the world to slap an attribute to the items, but the handler needs to be overwritten on each redraw. So basically this attribute is just used to check if a handler exists. If it does, we …

Fix hide unselected items

---

src/application.py
src/application.vala
src/canvas.py

Adds the option to scroll horizontally by holding shift. [See GNOME Circle Review](https://gitlab.gnome.org/Teams/Circle/-/issues/185).

Add shift to scroll horizontally

---

data/se.sjoerd.Graphs.gresource.xml
data/styles/matplotlib.mplstyle

A relatively simple change, but I just noticed we are shipping pretty much every style that comes bundled with standard matplotlib, except for the default matplotlib style. This adds the default matplotlib style.

Add matplotlib style

---

data/ui/curve_fitting.blp
data/ui/fitting_parameters.blp
src/application.vala
src/canvas.py
src/curve_fitting.py
src/curve_fitting.vala

Redesigns Curve Fitting dialog according to [GNOME Circle Review](https://gitlab.gnome.org/Teams/Circle/-/issues/185):
[Skärminspelning från 2023-12-11 14-40-07.webm](https://github.com/Sjoerd1993/Graphs/assets/68477016/05a5d860-f3da-47b5-a96f-de51a1ebf9b5)
The only point where I deviated is the ` The empty box at the bottom of the sidebar is still weird, I'd hide it when it's empty` comment. The results card there can only be empty when one of the values was wrong during initialization (e.g. when starting the curve fit while an invalid boundary or equation was set). Instead of hiding it, I put an error message in there instead.

Curve fitting redesign

---

src/application.py

Literally a two-character PR.
Forgot to use an `elif` instead of an `if` earlier, breaking the ctrl button plus zoom. (Pressing `ctrl` means that the comparison for the shift key is false, thus triggering the 'else` condition) 
This fixes that.

Fix ctrl button

---

data/ui/add_equation_window.blp
data/ui/figure_settings.blp
data/ui/fitting_parameters.blp

Uses homogenous entry rows where we've got multiple side-by-side. This finally fixes this stubborn bug where the entries become smaller when active
Before:
After:

Use homogenous rows

---

data/ui/figure_settings.blp

It's a bit of a bandaid solution, as it'd still be preferable to allow resizing to fewer columns. But GtkGridView reserves the vertical space it needs for the case when there's only one column available. This leads to a large amount of whitespace in the scrollbar in the style overview.
We can maybe take a closer look at this later, I couldn't find a direct solution for now. But I think for now at least for the coming release it's sensible to just fix the amount of columns to three, which solves this issue:

Fix style overview columns to three

---

data/ui/figure_settings.blp
data/ui/window.blp
src/application.py
src/canvas.py
src/data.py
src/figure_settings.py
src/ui.py

Hide all settings for each axis if they're currently not used.
Second screenshot is slightly extended compared to default height to show all relevant fields.

Hide unused axes settings

---

data/ui/curve_fitting.blp
src/utilities.py

Minor updates to the curve fitting dialog in line with the GNOME Circle Feedback.
Also adds support for superscript equations (e.g. y=x² instead of y=x^2), which was mainly added to fix this issue with the curve fitting but the fix has the added benefit that it works over all equation handling.

Update curve fitting

---

data/ui/figure_settings.blp
data/ui/style_editor.blp
data/ui/window.blp

- Removes the "hand" suffix for the direction in the axes limits so it's consistent with the rest of the application. (Could use it everywhere instead as well, but I guess removing it is somewhat cleaner)
- Fixes a capitalization in the subtitle of the text and label size, in the style editor.
- Removes the X and Y prefix when talking about e.g. "Bottom X axis", as the X/Y part is already implicitly specified when giving the direction.
- Change "Best" in the legend to "Auto", as the former is a bit confusing imo.

Minor string changes

---

data/ui/export_figure.blp
src/export_figure.py

Hides the dpi when exporting images in vector-based formats. It's meaningless to talk about pixel density in vector images, and this setting doesn't even have an impact on the exported figure (not even on the rendered size), so it's best to hide them when not applicable.
Also removes unsupported filetypes, those were broken from the beginning.

hide dpi with vector based images

---

data/se.sjoerd.Graphs.gschema.xml
data/ui/curve_fitting.blp
data/ui/fitting_parameters.blp
src/curve_fitting.py
src/curve_fitting.vala
src/misc.py
src/utilities.py

Adds the following options to the Curve Fitting dialog:
- **Equation**: Sets the equation that is currently used. I've set the default value to "Custom" for discoverability's sake, the idea there was that out of the box all entries are working and editable. Then when one discovers the setting, it is more obvious why this box is grayed out. The reason for not removing this box, is so that it's clear what the equation itself is that is being fitted to.
- **Optimization**: Sets the optimization algorithm that is being used for the fit. Typical Levenberg-Marquardt is the standard for most tools I've come across. But there may be reasons for prefering others.
- **Confidence bounds**: This sets the confidence bounds. Allowing this to turn them off, or to just set it to a multiple of the …

Add curve fitting options

---

data/ui/dialogs.blp
src/styles.py

Adds a "Delete Style" dialog when trying to delete a style, since this is a destructive action it should probably have a dialog. A toast would work as well if it comes with an undo button, but that's a bit more technical work so this works for now.

Add delete style dialog

---

data/ui/curve_fitting.blp
data/ui/item_box.blp
src/item_box.py
src/ui.py

> - [x] Some menu entries are not using Title Case, e.g. "Move items" should be "Move Items"
I think I've now got them all
> - [x] Clicking the rows with the equations doesn't do anything, which is surprising given that it has a hover state. I would have expected this to allow editing the equation or checking the checkbox.
Clicking them right now checks the checkbox.
> - [ ]  "Bottom Scale" and "Left Scale" are a bit unclear at first glance, especially in the simple/default case where there's just two axes. Maybe the scale menu entries could be "X Axis Scale" and "Y Axis Scale"?
This still needs to be fixed. An easy solution is to just use "X Axis Scale" and "Y Axis Scale" for left and bottom scale and "Right X Axis Scale" and "Top Y Axis Scale" for the right and top scale. But it may …

Adress more GNOME Circle Feedback

---

data/ui/help_overlay.blp
data/ui/item_box.blp
data/ui/window.blp
src/item_box.py

Some things from the GNOME Circle Feedback:
-  Ctrl+W should close the window
-  This context menu can be opened, but not navigated via keyboard:
Both are addressed now. The context menu's focus was disabled upon click, as it can scroll down in unexpected ways if there's a long list of items present. However this is at the cost of accessibility, so that fix has been reverted. This scrolling behaviour is probably a GTK-issue, but either way seems less present now probably since the latest changes with regard to breakpoints a while ago.

Implement GNOME Circle Checklist

---

src/data.py
src/parse_file.py

Makes the following adjustments to importing and header handling:
- Stops looking for headers when data is detected. This makes it such that comments and other data at the bottom are just ignored
- Only add X and Y data if _both_ data can be added, otherwise skip that row. This prevents errors when one of the data points was valid but the other one was not
- Use the getters and setters for the labels, this was broken when we moved the item class to Vala, the relevant code was still trying to assign the attribute directly.
- Do not add X and Y data if either of them returns None. This still parses as a float, but leads to errors when doing fitting or limit optimisations
- Just use the delimiter to detect headers, stop detecting whitespaces as first choice by default. As I feel using two …

Import and header adjustments

---

src/canvas.py

Greatly enhances performance (e.g. when panning or zooming with the touchpad) for stylesheets where the splines are not drawn whilst ticks are turned on. For example the FiveThirtyEight style sheet, which is quite laggy at the moment. Skipping this line whenever the relevant axis' spline is turned off greatly improves performance.
I'll keep issue #672 open for now, to keep that as a tracker (I'd like to see what parameters affect performance for instance, and check if we're doing any redundant renderings). But this goes a long way at least.

Only draw minor ticks if spine visible

---

README.md
data/ui/import.blp
po/graphs.pot

Updates pot file to the latest strings, and uses the suggested string for the delimiter in #660. I _think_ this should be the last string changes at all before next release. Unless we decide to change things in the Readme as well, but those shouldn't change the package itself or anything related to Weblate, so those are not covered in a string freeze.
Also, with PR #681, I think this is in a pretty decent stage before the next release. Of course, assuming no new bugs turn up, want to give it at least until somewhere next week. But releasing _before_ the TWIG issue of Friday the 19th seems realistic. (Perhaps the 12th). And of course, new screenshots needs to be added as well.
Probably want to have at least a screenshot of the main application in action, one with the new fancy style …

Minor language updates

---

src/data.py

Makes some tweaks to how labels are updated when removing and adding items:
- Generally the code is a bit more clean with the deleting part (I prefer the loop over the else-if statements)
- Now when deleting an item, it checks for each label if the corresponding axis is still occupied after deleting. If it is still occupied, it does not delete the label. This prevents the situation where you have two datasets with the same units, and then the axes labels dissapear when removing one of them. See screencast, as that may be clearer.
- If the list of data items is empty when loading the data set (so plot is empty), then it always ignores the axes labels and just overwrites those labels and places the data in the left/bottom axes.
General point of discussion: The last bullet point solves the …

Label update tweaks

---

src/data.py

When testing, I found that an error occurred when "Hide unselected items" was selected, and the Figure Settings was loaded. This is because it was trying to look for `item_,selected`, but this attribute needs to be retrieved using the getter/setter methods. Hence the error. This PR fixes that.

Fix unselected item getter

---

data/ui/add_equation_window.blp
data/ui/transform_window.blp

Sets the default widgets in the dialogs with entry rows. Such that when pressing enter on the entry row, the action is performed. (e.g. you can add an equation by pressing enter on the entry fields). I think this covers all such dialogs we have. Closes issue #693

set default widgets in dialogs

---

src/ui.py

The export data gave an error when there was no data open, this was due to that it's now a prop from data, and can't be retrieved using the getter we used before. This now properly gives a toast.

Fix export data

---

src/actions.py

This will probably redundant, once we fix #695. The fix there is not that difficult, just check upon the entry change if the value is parsable, and if it isn't make deactivate the button and maybe give a red error CSS. 
In the meantime, I noticed the error here isn't given as a string into the toast. So currently the toast is not working.

Fix modify toast

---

src/canvas.py

Fixes issue #691 
The problem is relatively obvious, when getting the pan points it uses the Matplotlib internal function `._get_pan_points(button, key, x, y)`.  This can sometimes return `None` for whatever reason, see also the original function here (line 4279 on [this code](https://fossies.org/linux/matplotlib/lib/matplotlib/axes/_base.py)). Matplotlib gets around this with the `if points is not None`, which we adapt. But we still try to retrieve the limits from this, even if it got `None`. 
The simple fix is to move the retrieval of the limits after this conditional as well. As we don't use it otherwise anyway. In fact, whenever 'points` is `None`, the rest of the method is not executed at all, so declaring the limits before the conditional is just wasted computational power anyway …

Fix NoneType on pan error

---

src/operations.py

Adds a toast when an operation has been performed and the data outside of the higlighted area is discarded. The message is somewhat verbose, but that's because I wanted to have the past-tense in there ("that **was** outside of the") as to make it extra clear that the data that is highlighted _after_ the operation is fine.
I know the general advice is to use informal title case, but for clarity's sake I followed the following exception here:
> In some cases, a heading can be given a more informal style by expressing it as a regular sentence. In this case:
> 
>   -  Write the heading as a sentence, including auxillary verbs and articles.
> 
>    - Use sentence capitalization.
> 
>    - Continue to use a bold font style.
>

Add discard toast

---

data/se.sjoerd.Graphs.appdata.xml.in.in
data/whats_new
src/application.py
src/canvas.py
src/window.vala

Sets an "Error" CSS when the input value on the translate/modify entries are invalid, also disables the corresponding button. As discussed in issue #700.
[Skärminspelning från 2024-01-03 10-11-24.webm](https://github.com/Sjoerd1993/Graphs/assets/68477016/218e7188-db17-4780-95ed-731c4a1987e8)

Set translate/modify entry css

---

po/graphs.pot

Just run gettext to update the pot file. Only real change (apart from the location of the lines in the code) is one more title case being added. 
Should be the last `pot` update before next release. I think we can push next release very soon (this week). If new things suddenly turn up in the GNOME Circle Review, we can probably push it in Graphs 1.7.1, as I'm not expecting really major UI-breaking stuff there.

Update pot file

---

data/se.sjoerd.Graphs.appdata.xml.in.in
meson.build
src/ui.py

Updates the version number to 1.7.0, as well as the appdata.
If everything is OK otherwise, I was planning to tag this commit (after being merged) as release 1.7.0, and release on Flathub+Snap.

Release 1.7.0

---

data/se.sjoerd.Graphs.appdata.xml.in.in
data/ui/edit_item.blp
data/ui/figure_settings.blp
data/ui/style_editor.blp
meson.build
po/graphs.pot

Fixes issue #717 
I was thinking of maybe pushing the 1.7.1 update already after merging this, but in principle I can wait until tomorrow so we could update the last localization for the languages that are at 99% now. 
It's okay to do it for the 1.7.2 patch, but if you have time maybe @sabriunal could update the last five strings or so in Turkish? Changed some of the strings close to release which didn't get updated. 
Same with German @cmkohnen.  Also, just a hand full of strings, would be nice to have those in the next update as well. My idea was to release the patch before the next TWIG release, as I notice in the statistics that that always brings a measurable wave in installs.

Update Title Case

---

src/data.py

Removes the filename from the subtitle, only shows the path there. The filename is redundant because it's in the main title, and this (path in subtitle, filename in regular title) is also exactly like GNOME Text Editor does it.

Remove filename from subtitle

---

src/operations.py

Closes #719
[Skärminspelning från 2024-01-11 14-23-19.webm](https://github.com/Sjoerd1993/Graphs/assets/68477016/9d7250d6-f5bd-4007-8054-b72e194c4919)
Hides highlight after performing an operation by setting its extents to an infinitesimally small area of (0,0). Data points located at x=0 do fall in between this infinitesimally small span either, I have tested that.

Hide highlight after operation

---

data/ui/style_editor.blp
src/styles.py

While working on a graph, I found the slider for the title and label font sizes to be a bit to coarse, being only able to be set to multiples of 10 percentage points.
This PR sets this to multiple of 5 percentage points. Also allows to set the sizes to be 50%. But I am open to keeping 100% as the minimum.

Tune labelsize chooser

---

src/data.py

Does not optimise limits for items that are hidden. I found it unintuitive if items are hidden, that these are still taken into account when doing optimise limits. Skipping those items make the following possible:
[Skärminspelning från 2024-01-17 08-17-17.webm](https://github.com/Sjoerd1993/Graphs/assets/68477016/bf0557ee-461e-4c41-b6cb-062bad58579e)
Which is thus useful if you have a bunch of datasets in the same project with different limits, and just want to toggle between them. When items are not hidden, but non-active, then they are still used when optimising the limits.

Do not optimise limits for hidden items
