src/add_equation_window.ui
src/datman.py
src/preferences.py
src/window.ui

This MR does the following:
- Add equation window can be closed with Esc
- Create `save_file_chooser` function for save dialogs (to avoid copy pasting multiple lines of code)
- Set file chooser dialogs as modal (they stick with the parent window)
- Cancel button closes the window and does nothing for file chooser
- Set Preferences window as modal
- Remove arrow from hamburger menu
Criticism welcome. :)

Improve UI

---

src/add_equation_window.ui
src/open_special.ui
src/pip_mode.ui
src/plot_settings.ui
src/rename_label_window.ui
src/sample_box.ui
src/transform_window.ui
src/window.ui

Fixes all indentation errors I've spotted. Also removes two closing brackets, who had no opening bracket.

Fix XML indentation and closing errors

---

src/preferences.py

Remove "config not found error" on startup

---

src/add_equation.py

see https://github.com/SjoerdB93/Graphs/issues/26

fix duplication issues adding equations

---

src/add_equation.py
src/config.json
src/data.py
src/datman.py
src/item_operations.py
src/preferences.py
src/preferences.ui
src/samplerow.py
src/transform_data.py
src/utilities.py

This allows for multiple items / files bearing the same visual name to be displayed simultaneously without overriding each other. I'm trying to update the config to implement changes discussed in https://github.com/SjoerdB93/Graphs/issues/26#issuecomment-1399338374 
Still needs testing, as I haven't tried every option yet

use unique identifiers for data management

---

src/main.py

use meson version string for about window

---

data/config.json
data/ui/add_data_advanced.ui
data/ui/preferences.ui
src/add_data_advanced.py
src/graphs.py
src/preferences.py

Add  option to import x and y labels automatically

---

src/item_operations.py
src/main.py

Merge fix of issue #45 into this PR

Fix selection on log scale

---

Graphs.doap

As the title says. Picked up perfectly by GNOME Builder.

add doap file

---

se.sjoerd.Graphs.json

fix manifest

---

data/ui/help_overlay.ui
src/add_data_advanced.py
src/add_equation.py
src/graphs.py
src/item_operations.py
src/plotting_tools.py
src/transform_data.py
src/utilities.py

I refactored some code, did some deduplication at places and fixed some minor bugs.
Some specific changes:
-  Fourier Transform no longer sorts x- and y-data in ascending order as it seems it's losing some information along the way which it shouldn't. 
- If the automatic label detection can't find labels using at least two whitespaces, it tries the same delimiter as for the rest of the dataset before giving up. Being unable to get two valid labels also no longer causes an error.
- When the imported data leads to a list of zero length, it skips that dataset during import instead of adding an invalid dataset to the list.
- Add_equation now uses the newly created create_data to create a new item
- I split up open_selection into open_selection_from_file and open_selection_from_dict
- I …

Code refactor, deduplication 

---

src/preferences.py

Fix config sync

---

data/ui/window.ui
src/main.py
src/plotting_tools.py

Well, this was a chore...
After finally understanding the mechanics behind Menu states (no thanks to documentation or other projects using this),
the view menu now functions like @bertob suggested in https://github.com/SjoerdB93/Graphs/issues/60

view menu improvements

---

data/styles/adwaita-dark.mplstyle
data/styles/adwaita.mplstyle

As the title says, keeps it in line with default config

change default font size in custom styles

---

data/ui/window.ui
src/graphs.py
src/window.py

I'm not 100% certain with the wording / line break and definitely open for suggestions

Add notice, when no data is loaded

---

src/preferences.py
src/utilities.py

fix startup

---

data/ui/window.ui

fixes https://github.com/SjoerdB93/Graphs/issues/110

rename third tool category

---

src/actions.py
src/add_data_advanced.py
src/ui.py

Adds a warning Dialog if trying to open a project whilst data is loaded.

Add warning dialog, when overriding data

---

data/ui/window.blp
src/actions.py
src/main.py
src/ui.py
tox.ini

For now, this just makes the sidebar automatically retract if the window size gets too small

Improve responsiveness

---

meson.build
src/add_equation.py
src/data.py
src/file_io.py
src/graphs.in
src/graphs.py
src/item_operations.py
src/main.py
src/plotting_tools.py
src/preferences.py
src/transform_data.py
src/ui.py
src/utilities.py
src/window.py
tox.ini

- fix transform window, equations not showing.
- shorter way to add toast to main window
- swap print() for logging
- define log verbosity via meson (future pr for proper dev version comming soon)
- catch exception trying to load an invalid project

miscallaneous fixes

---

data/ui/transform_window.blp
src/transform_data.py

based on https://github.com/SjoerdB93/Graphs/pull/144
Adds ability to discard unselected data, when using transform

Transform discard

---

src/add_equation.py
src/calculation.py
src/edit_item.py
src/operations.py
src/preferences.py

- Remove duplicate line in edit-item.py
- Simplify generating of function data
- fix linting

Small changes

---

data/config.json
data/ui/export_figure.blp
src/canvas.py
src/export_figure.py
src/preferences.py

Add transparent background option, change wording a bit and add a confirmation toast

Export figure improvements

---

data/styles/adwaita-dark.mplstyle
data/styles/adwaita.mplstyle
data/styles/bmh.mplstyle
data/styles/classic.mplstyle
data/styles/dark-background.mplstyle
data/styles/fivethirtyeight.mplstyle
data/styles/ggplot.mplstyle
data/styles/grayscale.mplstyle
data/styles/seaborn-bright.mplstyle
data/styles/seaborn-colorblind.mplstyle
data/styles/seaborn-dark-palette.mplstyle
data/styles/seaborn-dark.mplstyle
data/styles/seaborn-darkgrid.mplstyle
data/styles/seaborn-deep.mplstyle
data/styles/seaborn-muted.mplstyle
data/styles/seaborn-notebook.mplstyle
data/styles/seaborn-paper.mplstyle
data/styles/seaborn-pastel.mplstyle
data/styles/seaborn-poster.mplstyle
data/styles/seaborn-talk.mplstyle
data/styles/seaborn-ticks.mplstyle
data/styles/seaborn-white.mplstyle
data/styles/seaborn-whitegrid.mplstyle
data/styles/seaborn.mplstyle
data/styles/solarized-light.mplstyle
data/styles/tableau-colorblind10.mplstyle
data/ui/plot_styles.blp
src/canvas.py
src/plot_styles.py

As the title says. Lets you change the colors of each style

Add Colors to the plot style editor

---

src/canvas.py
src/graphs.py
src/item_box.py
src/utilities.py

The proof-of-concept is there, and it works quite well actually:
[Screencast from 2023-04-02 21-16-09.webm](https://user-images.githubusercontent.com/68477016/229374154-6d14f3e0-cba8-40ee-9d22-40e7b9ab04f1.webm)
TODO:

Change order of items by dragging and dropping the items

---

data/styles/classic.mplstyle
data/styles/dark-background.mplstyle
data/styles/fivethirtyeight.mplstyle
src/canvas.py
src/file_io.py
src/plot_styles.py
src/utilities.py

Ensure valid keys in a style, when parsing it. Also fix linting, classic color definition and use uppercase hex notation.

Small fixes & Ensure valid style

---

.github/workflows/main.yml
data/styles/classic.mplstyle
data/styles/dark-background.mplstyle
data/styles/fivethirtyeight.mplstyle
src/add_data_advanced.py
src/calculation.py
src/canvas.py
src/export_figure.py
src/file_io.py
src/graphs.py
src/item_box.py
src/main.py
src/misc.py
src/plot_settings.py
src/plot_styles.py
src/plotting_tools.py
src/preferences.py
src/ui.py
src/utilities.py

Adds a few extensions to flake8 that improve code quality quite a bit. Also fix most of the newly reported issues right away.

Extend flake

---

src/ui.py

Gives an extension to Project files, so that they're actually filtered properly.

Give project files .graphs extension

---

data/meson.build
data/ui/add_equation_window.blp
data/ui/export_figure.blp
meson.build
src/add_data_advanced.py
src/add_equation.py
src/export_figure.py
src/graphs.in
src/main.py
src/meson.build
src/plot_styles.py
src/preferences.py
src/ui.py
src/utilities.py

- save data files to /app/share/graphs instead of /app/share/graphs/graphs
- Pass on datadir instead of querying on runtime
- name widgets in dialogs uniformly and sort in order of visual appearance
- use os.path.join instead of string concatination

Small fixes & changes

---

src/canvas.py
src/edit_item.py
src/main.py
src/plot_styles.py

Just a quick change to use set comprehensions and a fix my local flake8 install suggested (I'm on my laptop currently)

use set compehensions and remove redundant list operator

---

src/actions.py
src/file_io.py
src/graphs.py
src/plotting_tools.py
src/ui.py
src/utilities.py

- Fix select all and select none shortkeys, the functions were still trying to set the selected mode through the item_menu variable which no longer exists. This fixes this.
- Set restore view to custom function to find limits. This gives a more consistent experience with loading data and such, but also the built-in "home" functionality has some bugs with specific edge cases that were solved in the custom function.

Minor bugfixes

---

src/file_io.py
src/graphs.py
src/ui.py

After the clipboard change, the clipboard was not properly saved anymore in project files. This PR changes this.

Properly save clipboard in projects

---

src/actions.py
src/graphs.py
src/ui.py

Fixes two bugs regarding projects.
Sadly due to sanboxing appending .graphs to any project won't work, so I had to remove this

Remove path extension

---

src/operations.py

Sometimes it happens that the actions seem unresponsive, only for me to find out that I am in highlight mode and no data is within my highlight. This gives the user a pop up to notify them if that is the case.

Raise toast when no data selected

---

data/ui/help_overlay.blp
data/ui/window.blp

- Adds missing hotkeys that were added, removes old ones. 
- Fixes tooltips on the different modes. Those were incorrect placeholders still.

Update hotkeys and tooltip

---

data/config.json
data/ui/plot_settings.blp
data/ui/preferences.blp
src/canvas.py
src/misc.py
src/plot_settings.py
src/preferences.py

Adds the ability to manually set the legend location

Add ability to set the legend location

---

data/se.sjoerd.Graphs.appdata.xml.in.in
data/whats_new

Adds changelog to whats_new and the appstream file release date still needs to be entered later

Add changelog

---

src/clipboard.py
src/graphs.py
src/plot_settings.py
src/plot_styles.py
src/ui.py

A few things my local install picked up, don't know why the github action didn't report them

fix linting

---

data/se.sjoerd.Graphs.appdata.xml.in.in
meson.build
se.sjoerd.Graphs.json

Sets version and date. I also tagged it and signed, but I do not know if github will pick this up

Release 1.5.0

---

src/canvas.py
src/plot_settings.py
src/plot_styles.py
tox.ini

Just a few fixes my local flake8 pointed out

small linting fixes

---

src/canvas.py
src/plotting_tools.py

Small refactors:
- shorten scale change on view menu action
- Refactor find_min_max to take in scale and datalist, so we don't have to differentiate between x and y axis twice

Small refactors

---

src/canvas.py
src/file_io.py
src/graphs.py
src/plotting_tools.py

Add support for .xry file types as gotten from Leybold X-Ray apparatus.
These are devices we use in my school. As the actual logic isn't that complicated and they are stored in a pretty weird format (ISO-8859-1), I figured, it can't hurt to include this functionality.
Sidenote: somehow the commits from my other pr slipped in here as well, these can be ignored, the relevant part are only a few lines in file_io.py

Add xry support

---

data/se.sjoerd.Graphs.appdata.xml.in.in
src/file_io.py
src/graphs.py
src/utilities.py

Adds initial support for files with only one column. Fixes issue #240

Add single column support

---

po/de.po
po/fr.po
po/graphs.pot
src/actions.py
src/add_equation.py
src/export_figure.py
src/file_io.py
src/graphs.py
src/operations.py
src/plot_styles.py
src/plotting_tools.py
src/preferences.py
src/rename.py
src/transform_data.py

Initial work towards translating code-defined strings. Some elements are still missing (mainly choosers, on which's output we depend, so we can't just change it on a whim)

translate codebase

---

data/meson.build
data/se.sjoerd.Graphs.gresource.xml
src/preferences.py
src/ui.py

As the title says.
This should yield marginally better performance and reduce file system overhead when launching the application.

Bundle whats_new and config.json inside gresource

---

data/se.sjoerd.Graphs.appdata.xml.in.in
data/whats_new
po/LINGUAS
po/de.po
po/fr.po
po/graphs.pot
po/nl.po
po/sv.po

As title says, adds a Dutch translation to Graphs. I've added the .po file for Swedish as well (hence the giant changelog), as that's the next language I will do. (Also, the final one I will do myself by hand, as I've run out of languages I'm fluent in then)

Add Dutch translation

---

data/se.sjoerd.Graphs.appdata.xml.in.in
data/whats_new
src/canvas.py

Fixes issue #259, should be reverted once it's fixed upstream but works nice for now. Doesn't seem to have clear drawbacks either.

Fix HiDPI scaling

---

src/actions.py
src/add_data_advanced.py
src/file_import.py
src/file_io.py
src/ui.py

Rewrite data export to work with GFile. Also move logic outside of file_io, since we already distinguish between single item and multiple in the caller function. This no longer uses `numpy.savetxt` since we always expect two-dimensional tuples for values thus reducing a lot of overhead intruduced by mentioned function.
Also refactor some logic.

Rewrite data export.

---

data/config.json
data/ui/add_data_advanced.blp
data/ui/preferences.blp
src/add_data_advanced.py
src/file_io.py
src/graphs.py
src/item.py
src/misc.py
src/plot_styles.py
src/preferences.py

As suggested in https://github.com/Sjoerd1993/Graphs/issues/251#issuecomment-1551692877, This reworks setting labels automatically. This drops the guess_headers config option in favour of that

Rework label adjustments

---

data/ui/edit_item.blp
src/actions.py
src/canvas.py
src/edit_item.py
src/file_io.py
src/graphs.py
src/item.py
src/item_box.py
src/main.py
src/operations.py
src/ui.py
src/utilities.py

Again sorry for the stacking. Based on https://github.com/Sjoerd1993/Graphs/pull/272.
An effort to support not only regular plotted data, but also text, shapes, etc. 
See proof of concept:

Item types

---

data/ui/plot_settings.blp
po/LINGUAS
po/POTFILES
po/graphs.pot
po/tr.po
src/plot_styles.py

**Mark 3 strings translatable from plot_styles.py**
**i18n: Add missing plot_styles.blp to POTFILES**
**i18n: Reorder some files in POTFILES**
**UI: Mark Color + number strings translatable**
**Fix renamed import file**
- Introduced via https://github.com/sabriunal/Graphs/commit/42c9207cd6cd77fbc74733399af1d18cae501a7d
**Update POT file**
**Add Turkish translation**

7 pacthes related to translation

---

src/actions.py
src/canvas.py
src/edit_item.py
src/graphs.py
src/item_box.py
src/misc.py
src/operations.py
src/plot_settings.py
src/plot_styles.py
src/plotting_tools.py
src/rename.py
src/ui.py

Refactor code regarding axis limits.
Axis limits are now stored inside the plot settings, making them persistent when opening and saving projects.

Make limits persistent.

---

src/file_import.py
src/file_io.py

Allows to import items from any saved project.

Allow import from project files.

---

src/canvas.py
src/file_io.py

- Create function for opening a writable stream
- Fix style writer
- Fix legend

Fix a few issues regarding file interaction.

---

.github/workflows/main.yml
snap/snapcraft.yaml

All the workflows are also passing. This is mergable now.

Snap Python fix and Workflow added 

---

blueprint-compiler.json
data/meson.build
data/se.sjoerd.Graphs.gresource.xml
data/ui/add_equation_window.blp
data/ui/add_style.blp
data/ui/dialogs.blp
data/ui/edit_item.blp
data/ui/export_figure.blp
data/ui/import.blp
data/ui/item_box.blp
data/ui/plot_settings.blp
data/ui/plot_styles.blp
data/ui/preferences.blp
data/ui/rename_window.blp
data/ui/style_box.blp
data/ui/style_color_box.blp
data/ui/transform_window.blp
data/ui/window.blp
src/actions.py
src/add_equation.py
src/plot_styles.py
src/ui.py

Dialogs, especially Adw.MessageDialogs are now stored in dialogs.blp and can be build using a new function in ui.
This requires a version bump in the blueprint-compiler, requiring slight syntax adjustments

Build dialogs dynamically.

---

src/export_figure.py

This is a workaround. The matplotlib implementation doesn't support file like objects, so creating an in-memory buffer isn't suitable here. Instead we have to create a temporary file, which should always have a path and be accessible by pythons inbuilt file functions, point matplotlib to that and move it in the correct place.

Use GFile for exporting figures.

---

README.md
snap/snapcraft.yaml

Added `blueprint-compiler` `v0.8.1` and added snap badge in the `README.md`

---

data/ui/add_equation_window.blp
data/ui/add_style.blp
data/ui/export_figure.blp
data/ui/import.blp
data/ui/rename_window.blp
data/ui/transform_window.blp
src/file_import.py
src/rename.py

fix https://github.com/Sjoerd1993/Graphs/issues/298

redesign action dialogs

---

src/main.py
src/ui.py

Similar to the pr using the inbuilt application reference.
Also remove deprecated use of FLAGS_NONE

use inbuilt appid

---

src/actions.py
src/add_equation.py
src/clipboard.py
src/export_figure.py
src/file_import.py
src/graphs.py
src/item.py
src/main.py
src/misc.py
src/plot_settings.py
src/preferences.py
src/utilities.py

- Streamline open and save process
- Check import options individually
- reference only preferences
- rename all references from config to preferences for consistency

Refactor Config.

---

data/ui/window.blp
src/actions.py
src/file_import.py
src/main.py
src/ui.py

Drop the advanced import option. Also use a MenuButton for adding again and split off import and equation. In the future adding text, and other items will get another section
I found that the keybind we used didn't work either way as it toggles between light and dark mode

drop advanced import

---

src/canvas.py

Fixes an issue where the legend would not get hidden properly if the legend was turned off. In the current main branch, if you turn off the legend it does not disappear until the graph is actually reloaded (not refreshed). This fixes that issue.

Fix legend

---

data/ui/window.blp
src/actions.py
src/main.py
src/ui.py
src/window.py

For the operations only invoked via their buttons, it is redundant to invoke a complete action only to have a few lines of code coupled to them.
This uses signal handlers to perform logic when the button is clicked.

Use functions for operations.

---

src/file_io.py
src/ui.py

When exporting write headers, if present. Also refactor file_io to shorten common operations.

Support writing headers to a file.

---

data/ui/add_equation_window.blp
data/ui/add_style.blp
data/ui/dialogs.blp
data/ui/edit_item.blp
data/ui/export_figure.blp
data/ui/import.blp
data/ui/item_box.blp
data/ui/plot_settings.blp
data/ui/plot_styles.blp
data/ui/preferences.blp
data/ui/window.blp
src/file_import.py
src/main.py
src/plot_styles.py

Apologies for the lack of contributions in the last couple of weeks. I've passed my final exams and had quite eventful weeks since then.
Follow HIG advice on text throughout the application. Use correct Typography.
Use "Figure" in favour of "Plot" or "Graph" (only in UI).

Linguistic improvements

---

src/add_equation.py
src/calculation.py
src/plot_settings.py
src/utilities.py
src/window.py

Instead of using either eval() or float() for converting a string to a float we define a custom function.
This makes use of a regular expression matching any number even respecting scientific notation.

Safer Number conversion

---

data/ui/plot_settings.blp
src/plot_settings.py

Make style change instantaneous and refactor the whole class slightly.

Refactor plot_settings window

---

src/plot_styles.py
src/ui.py

Apply new logic for editing plot styles.

Refactor plot style editor.

---

src/preferences.py

Handle key migration and template checking in one step. Also migrate
import_params if it were to change.

Refactor preferences

---

data/ui/plot_styles.blp
src/plot_styles.py

fix grid opacity

---

data/ui/add_style.blp
data/ui/export_figure.blp
data/ui/plot_settings.blp
data/ui/plot_styles.blp
data/ui/preferences.blp
data/ui/window.blp

implement changes based on recent [Design suggestions](https://gitlab.gnome.org/Teams/Circle/-/issues/185).
- Reword some items
- Remove indifferent descriptions
- Move Translate & Multiply to the bottom
- Redesign Translate and Multiply actions

UI changes

---

src/add_equation.py
src/canvas.py
src/clipboard.py
src/edit_item.py
src/export_figure.py
src/file_import.py
src/file_io.py
src/graphs.in
src/main.py
src/plot_settings.py
src/plot_styles.py
src/preferences.py
src/rename.py
src/transform_data.py
src/ui.py

- inline transient_for property
- use gproperty for some classes
- refactor canvas (use super for creating self.figure)
- drop useless span argument in Highlight constructor
- refactor AboutWindow
Using GObject based properties gives the added benefit of having some sort of typesafety and generifying object creation.

Use more GObject-Style code

---

data/ui/edit_item.blp
data/ui/plot_settings.blp
data/ui/plot_styles.blp
data/ui/preferences.blp

- Redesign preferences
- Remove redundant subtitles
- Linguistic/Contextual improvements

Ui Changes.

---

snap/snapcraft.yaml

Updates the blueprint version in the snap package to be the same version as used in Flatpak.

Update snap blueprint version

---

src/canvas.py
src/clipboard.py
src/data.py
src/export_figure.py
src/file_import.py
src/file_io.py
src/main.py
src/migrate.py
src/operations.py
src/utilities.py

Small fixes across the codebase from my testing and pylint analysis

small fixes

---

src/item.py
src/plot_styles.py
src/ui.py

Also fix issues regarding style change

only reload when edited style is in use

---

src/export_figure.py

Export figure got broken with the removal of the canvas reference, this fixes this issue.

Fix export figure

---

data/ui/window.blp

Mark three labels' strings from window.blp as translatable

data: Mark three strings translatable

---

data/ui/help_overlay.blp

fix help overlay

---

src/edit_item.py

Function was not called properly, making it impossible to load add item window

Fix edit item window

---

data/ui/figure_settings.blp
data/ui/window.blp
src/actions.py
src/canvas.py
src/main.py
src/meson.build
src/scales.py
src/ui.py

Add Radians Scale as a third option
Also implement bas structure for future custom scales

Radians scale

---

data/se.sjoerd.Graphs.gschema.xml
data/ui/figure_settings.blp
data/ui/preferences.blp
src/figure_settings.py
src/item.py
src/migrate.py
src/preferences.py

Remove default Figure Settings Values from Preferences.
Add Set as Default Button to Figure Settings

Reduce preferences

---

src/scales.py

Sometimes life is simple, this fixes said issue.
Fixes #437

Fix pan and zoom on custom scaling

---

src/actions.py
src/main.py
src/ui.py

fix https://github.com/Sjoerd1993/Graphs/issues/438.

update actions on scale change

---

src/utilities.py

After seeing @veggero fumble around in a video trying to insert a cotangent, I thought it would be good to add these extra trigonemetric functions as well. This PR adds support for cotangent, secant and cosecant.
See video [here](https://www.youtube.com/watch?v=nsz-jdP9xvg&t=359s) starting, around 5:14.

Adds more trignometric functions

---

src/scales.py
src/utilities.py

- hold local figure_settings reference
- reduce number of loops
- reduce duplicated logic
- fix linting

improve optimize limits

---

data/se.sjoerd.Graphs.gschema.xml
src/styles.py

Try to optimize style related functions.
- Don't loop over system styles as often as we know the exact path of files
- Make system style a setting (not to end users)
The last step is the base for an upcomming feature I try to add: Yaru style for snap packaging

Improve style functions

---

blueprint-compiler.json

Cleanup blueprint during build, following the PR @hfiguiere uploaded on the Flathub repo.

Cleanup blueprint

---

Graphs.doap
meson.build
src/data.py
src/figure_settings.py
src/figure_settings.vala
src/graphs.in
src/main.py
src/meson.build
src/misc.vala
src/operations.py
src/project.py
src/styles.py
src/window.py

This is a proof of concept in using the Vala language for classes that make heavy use of GObject based functions.
In this pr I've ported the FigureSettings class.
There are multiple benefits to this:
- Performance gain through compilation to binary
- Compile time errors and warnings just like blueprint, which could prevent regressions
- Type safety even for arrays and other more complex types
- Automatic generation of getter and setter methods
- More readable syntax for Properties and Signals
- Probably some funky stuff, that's complex to implement in python
- (If somehow needed: easier and more reliable access to c code)
This can be seen as just a suggestion and if this would be out of scope, I'm absolutely fine with that.

Suggestion: Use Vala for more GObject centric classes

---

data/ui/window.blp
src/canvas.py
src/main.py
src/project.py
src/styles.py
src/ui.py
src/window.py

Add a visual indicator if for some reason the canvas didn't load properly

add visual error on canvas fail

---

src/artist.py
src/canvas.py
src/figure_settings.vala
src/interfaces.vala
src/item.py
src/item.vala
src/meson.build

Add interfaces for classes, which will definitely remain implemented in python, but may be accessed from Vala.

implement interfaces for objects implemented in python

---

src/file_import.py
src/file_io.py
src/meson.build
src/parse_file.py
src/ui.py

Split of file parsing to separate file.
Also clean up general import logic:
- get rid of ImportSettings class
- only initialize window if there are modes to be configured

Split file parsing

---

src/artist.py
src/canvas.py
src/figure_settings.vala
src/interfaces.vala
src/item.py
src/item.vala

Remove split off for some interfaces, as it made code relly messy sometimes

cleanup interfaces

---

src/canvas.py

- Change hierarchy of axes
- Set legend axis during item set
Improves performance and fixes an issue with hide_unselected

refactor legend logic

---

src/curve_fitting.py

The Data class, which FittingParameterEntry inherits from, now requires a setting argument directly. So this is also needed in FittingParameterEntry.

fix curve fitting

---

data/ui/help_overlay.blp
data/ui/window.blp
src/actions.py
src/application.py
src/application.vala
src/canvas.py

See title. 
Still need to change the zooming logic so that it works on non-linear axes. Also, the way to detect if a ctrl is pressed is not my ideal, but for some reason the key_press event in the canvas is not registered. My guess is that this is because the canvas is not in focus, which is by design as we need to catch the shortkeys in the main application.
[Screencast from 2023-09-18 14-39-55.webm](https://github.com/Sjoerd1993/Graphs/assets/68477016/58bf3b36-5f41-4b9f-b512-1474a63d6f54)
Closes issue #491, also closes the last checkbox in #385 but I won't close that one until we've been accepted into GNOME circle, as new feedback will probably arise.

Implement ctrl+scroll and pinch to zoom gestures

---

src/operations.py

Simple PR, in the get_data method this now uses numpy instead of looping through all item elements in Python. Which should be a significant performance difference (relatively speaking). Also the syntax is cleaner.

Use numpy to get data

---

src/actions.py
src/canvas.py

make internal methods start with an underscore
add docstring to zoom()
some code simplification

prettify zoom logic

---

data/se.sjoerd.Graphs.gresource.xml
data/se.sjoerd.Graphs.gschema.xml
data/styles/yaru-dark.mplstyle
data/styles/yaru.mplstyle

like the title says. Also add both yaru and seaborn as supported system styles.

add yaru style

---

snap/snapcraft.yaml

The current state of the snap. Didn't get the option to change styles.

various changes for the latest release

---

src/application.py
src/styles.py

Add a watchdog for the style directory so in case the used style gets deleted by whatever means, a reload is queued

add watchdog for style directory

---

data/ui/add_equation_window.blp
data/ui/add_style.blp
data/ui/curve_fitting.blp
data/ui/export_figure.blp
data/ui/import.blp
data/ui/style_window.blp
data/ui/transform_window.blp

Mostly fixes shadows in the styles editor

use Adw.ToolbarView

---

data/styles/fivethirtyeight.mplstyle
src/migrate.py
src/utilities.py

Migrates user styles. If the style differs from a template or doesn't have one it is kept, else it is just deleted.

Migrate Styles

---

data/ui/fitting_parameters.blp
po/graphs.pot
src/curve_fitting.py

Adds some translatable strings related to the curve fitting, which I previously neglected.

Update pot file

---

data/se.sjoerd.Graphs.gschema.xml
data/ui/preferences.blp
src/add_equation.py
src/curve_fitting.py
src/item.py
src/migrate.py
src/operations.py
src/parse_file.py
src/preferences.vala

As discussed removes the preferences for the default x and y position.
This also means items no longer need to get a reference to the application on init.
Also optimize xry import slightly.

Remove default position setting & optimize xry import

---

src/canvas.py
src/curve_fitting.py
src/data.py
src/parse_file.py

- use zip in favour of enumerate wherever possible
- small optimizations specific to xry
- small optimizations specific to columns
- fix skip rows with single column file

small optimizations

---

src/actions.py
src/canvas.py
src/curve_fitting.py
src/data.py
src/migrate.py
src/operations.py
src/parse_file.py
src/styles.py
src/utilities.py

Based on: #547 
General code cleanup throughout the project

General cleanup

---

data/styles/classic.mplstyle
data/styles/dark-background.mplstyle
data/styles/fivethirtyeight.mplstyle
data/styles/grayscale.mplstyle
src/figure_settings.py
src/file_io.py
src/meson.build
src/migrate.py
src/style_io.py
src/styles.py
src/ui.py

- Disallow the usage of savefig parameters in styles
- split of file parsing and writing
- misc fixes
- Use __iter__ functions for iterating over directories and models

General improvements and fixes

---

src/actions.py
src/application.py
src/artist.py
src/canvas.py
src/curve_fitting.py
src/data.py
src/figure_settings.py
src/item.py
src/styles.py

Adds a FillItem.
This is both the foundation for the current fill inside curve_fitting and future fills under select curves.
Also use tuples in cases, where arraylikes shouldn't be mutable

implement FillItem

---

src/styles.py

Calls update_style upon init of the style manager, as `self._system_style_params` needs to be initialised. Otherwise the current main branch does not launch.

Update style upon init

---

src/parse_file.py

Parse xry files progressively instead of loading the whole file into memory.

parse xry progressively

---

src/data.py
src/misc.py

Also improve performance of certain operations like iterating

Add Type Hints to data.py

---

data/ui/style_editor.blp
src/styles.py

- Move axis related options up
- Hide linewidth and markersize if they aren't enabled

improve style editor

---

data/ui/figure_settings.blp
src/actions.py
src/data.py
src/figure_settings.py
src/operations.py
src/style_io.py

- Allow editing bottom and left axis if no data is present
- Use generator expressions if better suited
- fix lining
- cleanup color deduplication

small improvements

---

data/se.sjoerd.Graphs.gschema.xml
data/ui/preferences.blp
src/data.py
src/migrate.py
src/preferences.vala

also fixed an accidental regression

drop handle-duplicates preference

---

src/actions.py
src/application.py
src/data.py
src/data.vala
src/ui.py

Adds the foundation for the overlay I described in #591

Make is_empty a property

---

src/styles.py
src/utilities.py
src/window.vala

Sets headerbar CSS equal to style background
[Skärminspelning från 2023-11-20 14-32-01.webm](https://github.com/Sjoerd1993/Graphs/assets/68477016/9bf2ff78-7d32-4a0c-9ada-f17ab0e721f0)

Set headerbar css on style change

---

src/actions.py
src/application.py
src/data.py
src/figure_settings.py
src/styles.py

Excludes all limits and selection
Also fix linting
Also move action scale logic to actions.py

add figure settings changes to history

---

data/ui/edit_item.blp

Simple and quick PR, makes the position for the items translatable.

Make positions translatable

---

src/curve_fitting.py

Adds an error highlight to the relevant entry in the curve fitting dialog when a wrong entry is put in.
Also cleans the logic there a bit.
[Skärminspelning från 2023-12-08 10-32-35.webm](https://github.com/Sjoerd1993/Graphs/assets/68477016/fcef485c-3d5b-4e54-a8dd-9f8edd029ace)
Closes issue #626

Add error highlight with wrong entries

---

data/se.sjoerd.Graphs.appdata.xml.in.in
data/ui/style_editor.blp
data/whats_new
src/styles.py

Adds the option to set the label size as well. Almost forgot about this, but it's been a thing I've wanted to add since the titel size option has been implemented. Otherwise I don't really have any UI-facing changes planned that would require string changes. (Except for PR #656 )

Add label size option

---

data/ui/window.blp
src/application.py

Atop a general refactor this fixes a few issues:
Sensitivity of the buttons is now handled correctly.
Fixed condition regarding an empty string.
Buttons can no longer be sensitive if no data is selected

improve translate/multiply handling

---

data/se.sjoerd.Graphs.appdata.xml.in.in

appdata: Update appdata

---

data/meson.build

- Use appstreamcli to validate appdata
Part of: https://gitlab.gnome.org/GNOME/Initiatives/-/issues/46

appdata: Improve appdata for AppStream 1.0
